In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest

In [3]:
authLogsDF= pd.read_csv(r"C:\Users\rishu\Downloads\AuthLogs_ML_Ready_3000_v3.csv")

In [4]:
authLogsDF.head()

,AuthType,BrowserID,City,Country,EmailId,EventID,EventName,EventType,IPAddress,Lang,...,departmentName,serviceGroupId,month,user fingerprinting,device fingerprinting,Latitude,Longitude,IsVPN,IsProxy,IPReputationScore
0,Password,BROWSER_007,Kolkata,India,user_197@example.com,EV2801,Login,Failure,10.20.2.10,en,...,IT,1.0,Sep,UF_8EB9FAB8D39B,DEVICE_016,22.549211,88.329549,No,No,82
1,OAuth,BROWSER_029,Mumbai,India,user_33@example.com,EV2190,Login,Success,10.20.0.3,hi,...,Sales,10.0,Oct,UF_D019D721DDE0,DEVICE_006,19.064294,72.875276,Yes,No,65
2,Biometric,BROWSER_006,Delhi,India,user_21@example.com,EV2817,Login,Failure,10.20.1.2,hi,...,HR,7.0,Apr,UF_E769EA64EDB5,DEVICE_031,28.639385,77.219436,No,No,98
3,Password,BROWSER_006,Hyderabad,India,user_86@example.com,EV1251,Password Reset,Success,10.20.3.16,hi,...,Finance,10.0,Jun,UF_7D8CAC73FE4F,DEVICE_012,17.398749,78.497191,No,Yes,41
4,OAuth,BROWSER_010,Pune,India,user_61@example.com,EV1766,Login,Success,10.20.1.25,en,...,Support,NaN,Sep,UF_499,DEVICE_023,18.503030,73.873614,No,No,90

In [5]:
print("Total Rows:", authLogsDF.count())

Total Rows: AuthType                 3000
BrowserID                3000
City                     3000
Country                  3000
EmailId                  3000
EventID                  3000
EventName                3000
EventType                3000
IPAddress                3000
Lang                     3000
Location                 3000
LoginAlert               3000
MobileNo                 2049
MultiFactorType          2507
OTPSendOn                2454
OTPType                  2319
Reason                   3000
RememberDevice           3000
ServiceId                3000
ServiceName              3000
ServiceState             3000
SessionID                3000
State                    3000
TimeStamp                3000
TokenID                  3000
UId                      3000
UserAgent                3000
UserId                   2049
UserName                 3000
WithGeoFencing           3000
departmentName           3000
serviceGroupId           2049
month                    3000
user fingerprinting      3000
device fingerprinting    3000
Latitude                 3000
Longitude                3000
IsVPN                    3000
IsProxy                  3000
IPReputationScore        3000
dtype: int64

In [6]:
print(authLogsDF.dtypes)

AuthType                  object
BrowserID                 object
City                      object
Country                   object
EmailId                   object
EventID                   object
EventName                 object
EventType                 object
IPAddress                 object
Lang                      object
Location                  object
LoginAlert                object
MobileNo                 float64
MultiFactorType           object
OTPSendOn                 object
OTPType                   object
Reason                    object
RememberDevice            object
ServiceId                 object
ServiceName               object
ServiceState              object
SessionID                 object
State                     object
TimeStamp                 object
TokenID                   object
UId                       object
UserAgent                 object
UserId                   float64
UserName                  object
WithGeoFencing            object
departmentName            object
serviceGroupId           float64
month                     object
user fingerprinting       object
device fingerprinting     object
Latitude                 float64
Longitude                float64
IsVPN                     object
IsProxy                   object
IPReputationScore          int64
dtype: object

In [7]:
print("\nFirst 5 Rows:")
display(authLogsDF.head())

First 5 Rows:

,AuthType,BrowserID,City,Country,EmailId,EventID,EventName,EventType,IPAddress,Lang,...,departmentName,serviceGroupId,month,user fingerprinting,device fingerprinting,Latitude,Longitude,IsVPN,IsProxy,IPReputationScore
0,Password,BROWSER_007,Kolkata,India,user_197@example.com,EV2801,Login,Failure,10.20.2.10,en,...,IT,1.0,Sep,UF_8EB9FAB8D39B,DEVICE_016,22.549211,88.329549,No,No,82
1,OAuth,BROWSER_029,Mumbai,India,user_33@example.com,EV2190,Login,Success,10.20.0.3,hi,...,Sales,10.0,Oct,UF_D019D721DDE0,DEVICE_006,19.064294,72.875276,Yes,No,65
2,Biometric,BROWSER_006,Delhi,India,user_21@example.com,EV2817,Login,Failure,10.20.1.2,hi,...,HR,7.0,Apr,UF_E769EA64EDB5,DEVICE_031,28.639385,77.219436,No,No,98
3,Password,BROWSER_006,Hyderabad,India,user_86@example.com,EV1251,Password Reset,Success,10.20.3.16,hi,...,Finance,10.0,Jun,UF_7D8CAC73FE4F,DEVICE_012,17.398749,78.497191,No,Yes,41
4,OAuth,BROWSER_010,Pune,India,user_61@example.com,EV1766,Login,Success,10.20.1.25,en,...,Support,NaN,Sep,UF_499,DEVICE_023,18.503030,73.873614,No,No,90

In [8]:
print("===== Missing Value Analysis =====")

missingDF = (
    authLogsDF.isnull()
    .sum()
    .reset_index(name="MissingCount")
)

missingDF["MissingPercentage"] = (
    missingDF["MissingCount"] / len(authLogsDF) * 100
)

missingDF = missingDF[
    missingDF["MissingCount"] > 0
].sort_values(
    "MissingCount",
    ascending=False
)

print(missingDF)

===== Missing Value Analysis =====
              index  MissingCount  MissingPercentage
12         MobileNo           951          31.700000
27           UserId           951          31.700000
31   serviceGroupId           951          31.700000
15          OTPType           681          22.700000
14        OTPSendOn           546          18.200000
13  MultiFactorType           493          16.433333

In [9]:
print("===== Missing Values by Event Name =====")

for col in [
    "MobileNo",
    "UserId",
    "serviceGroupId",
    "OTPType",
    "OTPSendOn",
    "MultiFactorType"
]:
    
    print(f"\n--- {col} ---")
    
    print(
        authLogsDF.groupby("EventName")[col]
        .apply(lambda x: x.isna().sum())
    )

===== Missing Values by Event Name =====

--- MobileNo ---
EventName
Account Unlock        0
Login               951
Logout                0
OTP Verification      0
Password Reset        0
Name: MobileNo, dtype: int64

--- UserId ---
EventName
Account Unlock        0
Login               951
Logout                0
OTP Verification      0
Password Reset        0
Name: UserId, dtype: int64

--- serviceGroupId ---
EventName
Account Unlock        0
Login               951
Logout                0
OTP Verification      0
Password Reset        0
Name: serviceGroupId, dtype: int64

--- OTPType ---
EventName
Account Unlock      122
Login               146
Logout              147
OTP Verification    135
Password Reset      131
Name: OTPType, dtype: int64

--- OTPSendOn ---
EventName
Account Unlock       99
Login               129
Logout               87
OTP Verification    127
Password Reset      104
Name: OTPSendOn, dtype: int64

--- MultiFactorType ---
EventName
Account Unlock       85
Login                91
Logout              110
OTP Verification     99
Password Reset      108
Name: MultiFactorType, dtype: int64

In [10]:
print("===== Duplicate Record Analysis =====")

duplicateCount = authLogsDF.duplicated().sum()

print("Total Duplicate Rows:", duplicateCount)
print(
    "Duplicate Percentage:",
    round((duplicateCount / len(authLogsDF)) * 100, 2),
    "%"
)

===== Duplicate Record Analysis =====
Total Duplicate Rows: 0
Duplicate Percentage: 0.0 %

In [11]:
print("===== Event Name Distribution =====")

eventNameDF = (
    authLogsDF["EventName"]
    .value_counts()
    .reset_index()
)

eventNameDF.columns = ["EventName", "Count"]

eventNameDF["Percentage"] = (
    eventNameDF["Count"] / len(authLogsDF) * 100
).round(2)

print(eventNameDF)

===== Event Name Distribution =====
          EventName  Count  Percentage
0             Login   1379       45.97
1  OTP Verification    433       14.43
2    Password Reset    416       13.87
3            Logout    401       13.37
4    Account Unlock    371       12.37

In [12]:
print("===== Event Type Distribution =====")

eventTypeDF = (
    authLogsDF["EventType"]
    .value_counts()
    .reset_index()
)

eventTypeDF.columns = ["EventType", "Count"]

eventTypeDF["Percentage"] = (
    eventTypeDF["Count"] / len(authLogsDF) * 100
).round(2)

print(eventTypeDF)

===== Event Type Distribution =====
  EventType  Count  Percentage
0   Success   1767       58.90
1   Failure    871       29.03
2   Warning    362       12.07

In [13]:
print("===== Event Name vs Event Type =====")

eventMatrixDF = pd.crosstab(
    authLogsDF["EventName"],
    authLogsDF["EventType"]
)

print(eventMatrixDF)

===== Event Name vs Event Type =====
EventType         Failure  Success  Warning
EventName
Account Unlock        128      217       26
Login                 359      800      220
Logout                122      242       37
OTP Verification      140      256       37
Password Reset        122      252       42

In [14]:
print("===== Login Count per User =====")

userLoginDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .groupby("UserName")
    .size()
    .reset_index(name="LoginCount")
    .sort_values("LoginCount", ascending=False)
)

print(userLoginDF.head(20))

===== Login Count per User =====
     UserName  LoginCount
229   user_37          16
286   user_81          11
201  user_285          11
12    user_11          11
270   user_68          11
50   user_145          10
304  user_954          10
254   user_55          10
61   user_155          10
67   user_160          10
171  user_257          10
308   user_99          10
42   user_138          10
183  user_268          10
165  user_250          10
297   user_90           9
44    user_14           9
176  user_261           9
208  user_291           9
48   user_143           9

In [56]:
print("===== Login Count Distribution =====")

print(userLoginDF["LoginCount"].describe())

===== Login Count Distribution =====
count    311.000000
mean       4.434084
std        2.602975
min        1.000000
25%        2.000000
50%        4.000000
75%        6.000000
max       16.000000
Name: LoginCount, dtype: float64

In [57]:
print("===== Unique IPs per User =====")

userIPDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .groupby("UserName")["IPAddress"]
    .nunique()
    .reset_index(name="UniqueIPCount")
    .sort_values("UniqueIPCount", ascending=False)
)

print(userIPDF.head(20))

print("\n===== Unique IP Distribution =====")
print(userIPDF["UniqueIPCount"].describe())

===== Unique IPs per User =====
     UserName  UniqueIPCount
242   user_45              6
229   user_37              5
300   user_92              5
171  user_257              5
92   user_183              5
14   user_111              5
61   user_155              5
115  user_203              5
166  user_251              4
208  user_291              4
38   user_134              4
131  user_218              4
269   user_67              4
44    user_14              4
262   user_60              4
185   user_27              4
114  user_202              4
234    user_4              4
183  user_268              4
168  user_253              4

===== Unique IP Distribution =====
count    311.000000
mean       2.189711
std        0.993214
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        6.000000
Name: UniqueIPCount, dtype: float64

In [58]:
print("===== Unique Browsers per User =====")

userBrowserDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .groupby("UserName")["BrowserID"]
    .nunique()
    .reset_index(name="UniqueBrowserCount")
    .sort_values("UniqueBrowserCount", ascending=False)
)

print(userBrowserDF.head(20))

print("\n===== Unique Browser Distribution =====")
print(userBrowserDF["UniqueBrowserCount"].describe())

===== Unique Browsers per User =====
     UserName  UniqueBrowserCount
229   user_37                   5
242   user_45                   5
171  user_257                   5
48   user_143                   4
300   user_92                   4
33   user_129                   4
14   user_111                   4
32   user_128                   4
61   user_155                   4
115  user_203                   4
1      user_1                   4
189  user_273                   4
234    user_4                   4
262   user_60                   4
201  user_285                   3
77    user_17                   3
200  user_284                   3
215  user_298                   3
204  user_288                   3
208  user_291                   3

===== Unique Browser Distribution =====
count    311.000000
mean       1.845659
std        0.862464
min        1.000000
25%        1.000000
50%        2.000000
75%        2.000000
max        5.000000
Name: UniqueBrowserCount, dtype: float64

In [59]:
print("===== Unique Devices per User =====")

userDeviceDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .groupby("UserName")["device fingerprinting"]
    .nunique()
    .reset_index(name="UniqueDeviceCount")
    .sort_values("UniqueDeviceCount", ascending=False)
)

print(userDeviceDF.head(20))

print("\n===== Unique Device Distribution =====")
print(userDeviceDF["UniqueDeviceCount"].describe())

===== Unique Devices per User =====
     UserName  UniqueDeviceCount
171  user_257                  5
229   user_37                  5
32   user_128                  4
61   user_155                  4
300   user_92                  4
1      user_1                  4
234    user_4                  4
262   user_60                  4
33   user_129                  4
189  user_273                  4
122   user_21                  4
48   user_143                  4
183  user_268                  3
168  user_253                  3
51   user_146                  3
176  user_261                  3
286   user_81                  3
237   user_41                  3
60   user_154                  3
44    user_14                  3

===== Unique Device Distribution =====
count    311.000000
mean       1.832797
std        0.813803
min        1.000000
25%        1.000000
50%        2.000000
75%        2.000000
max        5.000000
Name: UniqueDeviceCount, dtype: float64

In [60]:
print("===== Unique States per User =====")

userStateDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .groupby("UserName")["State"]
    .nunique()
    .reset_index(name="UniqueStateCount")
    .sort_values("UniqueStateCount", ascending=False)
)

print(userStateDF.head(20))

print("\n===== Unique State Distribution =====")
print(userStateDF["UniqueStateCount"].describe())

===== Unique States per User =====
     UserName  UniqueStateCount
115  user_203                 7
87   user_179                 7
60   user_154                 7
109  user_199                 6
232   user_39                 6
104  user_194                 6
269   user_67                 6
270   user_68                 6
176  user_261                 6
300   user_92                 6
229   user_37                 6
4    user_101                 6
211  user_294                 6
286   user_81                 5
53   user_148                 5
261    user_6                 5
288   user_83                 5
67   user_160                 5
278   user_75                 5
92   user_183                 5

===== Unique State Distribution =====
count    311.000000
mean       3.112540
std        1.390128
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        7.000000
Name: UniqueStateCount, dtype: float64

In [61]:
print("===== Consecutive Login Location Changes =====")

loginDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .copy()
)

loginDF["LoginTime"] = pd.to_datetime(
    loginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

loginDF = loginDF.sort_values(
    ["UserName", "LoginTime"]
)

loginDF["PreviousState"] = (
    loginDF.groupby("UserName")["State"]
    .shift(1)
)

loginDF["PreviousLatitude"] = (
    loginDF.groupby("UserName")["Latitude"]
    .shift(1)
)

loginDF["PreviousLongitude"] = (
    loginDF.groupby("UserName")["Longitude"]
    .shift(1)
)

loginDF["TimeDifferenceMinutes"] = (
    loginDF["LoginTime"] -
    loginDF.groupby("UserName")["LoginTime"].shift(1)
).dt.total_seconds() / 60

locationChangeDF = loginDF[
    (loginDF["PreviousState"].notna()) &
    (loginDF["State"] != loginDF["PreviousState"])
]

print("Total Login Events:", len(loginDF))
print("Location Changed:", len(locationChangeDF))

print(
    locationChangeDF[
        [
            "UserName",
            "LoginTime",
            "PreviousState",
            "State",
            "TimeDifferenceMinutes"
        ]
    ]
    .head(20)
)

===== Consecutive Login Location Changes =====
Total Login Events: 1379
Location Changed: 892
      UserName           LoginTime  PreviousState          State  \
2469    user_1 2026-07-17 15:27:00     Tamil Nadu      Karnataka
712     user_1 2026-08-08 10:50:00      Karnataka      Telangana
1794    user_1 2026-11-21 06:54:00      Telangana     Tamil Nadu
1303    user_1 2026-12-22 13:04:00     Tamil Nadu  Uttar Pradesh
1207    user_1 2027-02-14 00:27:00  Uttar Pradesh      Karnataka
2115    user_1 2027-03-21 16:24:00      Karnataka      Telangana
2503   user_10 2026-11-30 09:35:00      Karnataka    Maharashtra
151    user_10 2027-01-05 04:34:00    Maharashtra     Tamil Nadu
2887   user_10 2027-04-08 05:28:00     Tamil Nadu  Uttar Pradesh
1783  user_101 2026-04-30 20:48:00      Telangana     Tamil Nadu
1511  user_101 2026-10-29 17:45:00     Tamil Nadu          Delhi
2042  user_101 2026-12-17 11:48:00          Delhi    Maharashtra
1683  user_101 2027-02-20 03:16:00    Maharashtra      Karnataka
2837  user_101 2027-03-16 03:49:00      Karnataka    West Bengal
561   user_103 2027-01-04 12:41:00     Tamil Nadu    West Bengal
2291  user_103 2027-01-05 18:50:00    West Bengal      Telangana
2642  user_103 2027-01-22 11:36:00      Telangana     Tamil Nadu
959   user_103 2027-03-04 01:29:00     Tamil Nadu    West Bengal
2399  user_104 2027-02-15 21:34:00    Maharashtra          Delhi
893   user_105 2026-11-21 12:23:00     Tamil Nadu    West Bengal

      TimeDifferenceMinutes
2469                 7526.0
712                 31403.0
1794               112406.0
1303                45010.0
1207                77003.0
2115                20320.0
2503               203005.0
151                  6501.0
2887               133974.0
1783               155416.0
1511               261897.0
2042                70203.0
1683                88447.0
2837                11406.0
561                399877.0
2291                 1809.0
2642                23065.0
959                 58433.0
2399                37056.0
893                 71391.0

In [62]:
print("===== Corrected Login Distance Analysis =====")

# Only Login events
loginDF = (
    authLogsDF[
        authLogsDF["EventName"] == "Login"
    ]
    .copy()
)

# Convert Timestamp
loginDF["LoginTime"] = pd.to_datetime(
    loginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

# Sort chronologically for each user
loginDF = loginDF.sort_values(
    ["UserName", "LoginTime"]
)

# Previous login information
loginDF["PreviousState"] = (
    loginDF.groupby("UserName")["State"]
    .shift(1)
)

loginDF["PreviousLatitude"] = (
    loginDF.groupby("UserName")["Latitude"]
    .shift(1)
)

loginDF["PreviousLongitude"] = (
    loginDF.groupby("UserName")["Longitude"]
    .shift(1)
)

loginDF["PreviousLoginTime"] = (
    loginDF.groupby("UserName")["LoginTime"]
    .shift(1)
)

# Time difference
loginDF["TimeDifferenceMinutes"] = (
    loginDF["LoginTime"] -
    loginDF["PreviousLoginTime"]
).dt.total_seconds() / 60

===== Corrected Login Distance Analysis =====

In [63]:
print(
    loginDF[
        [
            "UserName",
            "LoginTime",
            "PreviousState",
            "State",
            "PreviousLatitude",
            "PreviousLongitude",
            "Latitude",
            "Longitude",
            "TimeDifferenceMinutes"
        ]
    ].head(10)
)

     UserName           LoginTime  PreviousState          State  \
1311   user_0 2026-07-12 10:00:00            NaN    Maharashtra
763    user_1 2026-07-12 10:01:00            NaN     Tamil Nadu
2469   user_1 2026-07-17 15:27:00     Tamil Nadu      Karnataka
712    user_1 2026-08-08 10:50:00      Karnataka      Telangana
2211   user_1 2026-09-04 05:28:00      Telangana      Telangana
1794   user_1 2026-11-21 06:54:00      Telangana     Tamil Nadu
1303   user_1 2026-12-22 13:04:00     Tamil Nadu  Uttar Pradesh
1207   user_1 2027-02-14 00:27:00  Uttar Pradesh      Karnataka
1216   user_1 2027-03-07 13:44:00      Karnataka      Karnataka
2115   user_1 2027-03-21 16:24:00      Karnataka      Telangana

      PreviousLatitude  PreviousLongitude   Latitude  Longitude  \
1311               NaN                NaN  19.085975  72.851526
763                NaN                NaN  13.094325  80.268458
2469         13.094325          80.268458  12.971841  77.596447
712          12.971841          77.596447  17.399299  78.492123
2211         17.399299          78.492123  17.394949  78.495573
1794         17.394949          78.495573  13.085818  80.283116
1303         13.085818          80.283116  26.828612  80.951533
1207         26.828612          80.951533  12.975154  77.626061
1216         12.975154          77.626061  12.992760  77.576645
2115         12.992760          77.576645  17.410193  78.496623

      TimeDifferenceMinutes
1311                    NaN
763                     NaN
2469                 7526.0
712                 31403.0
2211                38558.0
1794               112406.0
1303                45010.0
1207                77003.0
1216                31037.0
2115                20320.0

In [64]:
print("===== Distance Between Consecutive Logins =====")

R = 6371  # Earth radius in KM

lat1 = np.radians(loginDF["PreviousLatitude"])
lon1 = np.radians(loginDF["PreviousLongitude"])

lat2 = np.radians(loginDF["Latitude"])
lon2 = np.radians(loginDF["Longitude"])

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    np.sin(dlat / 2) ** 2
    + np.cos(lat1)
    * np.cos(lat2)
    * np.sin(dlon / 2) ** 2
)

c = 2 * np.arctan2(
    np.sqrt(a),
    np.sqrt(1 - a)
)

loginDF["DistanceKM"] = R * c

===== Distance Between Consecutive Logins =====

In [65]:
print(
    loginDF[
        loginDF["PreviousState"].notna()
    ]["DistanceKM"].describe()
)

count    1068.000000
mean      924.996601
std       553.302261
min         0.274045
25%       501.199313
50%      1080.669223
75%      1307.686809
max      1759.129952
Name: DistanceKM, dtype: float64

In [66]:
print(
    loginDF[
        [
            "UserName",
            "PreviousState",
            "State",
            "TimeDifferenceMinutes",
            "DistanceKM"
        ]
    ]
    .dropna(subset=["DistanceKM"])
    .sort_values("DistanceKM", ascending=False)
    .head(20)
)

      UserName PreviousState       State  TimeDifferenceMinutes   DistanceKM
174     user_2         Delhi  Tamil Nadu               237932.0  1759.129952
1701  user_128         Delhi  Tamil Nadu                82710.0  1759.127065
146   user_179         Delhi  Tamil Nadu                55675.0  1758.448644
2754  user_224         Delhi  Tamil Nadu                11288.0  1758.413339
2085  user_129         Delhi  Tamil Nadu                68692.0  1758.299286
1511  user_101    Tamil Nadu       Delhi               261897.0  1757.975121
2315  user_134         Delhi  Tamil Nadu                 7574.0  1757.890601
2870  user_148    Tamil Nadu       Delhi                11780.0  1757.750257
555    user_85    Tamil Nadu       Delhi                94632.0  1757.032981
2139  user_293         Delhi  Tamil Nadu                32846.0  1756.901170
394   user_168         Delhi  Tamil Nadu               399753.0  1756.806855
839   user_292         Delhi  Tamil Nadu                 1649.0  1756.651277
842   user_198    Tamil Nadu       Delhi                40835.0  1755.916814
2786  user_182    Tamil Nadu       Delhi               325778.0  1755.820922
2202  user_128    Tamil Nadu       Delhi                 3974.0  1755.727691
167   user_173    Tamil Nadu       Delhi                 1873.0  1755.611579
837   user_234    Tamil Nadu       Delhi                24551.0  1755.596216
694   user_202         Delhi  Tamil Nadu                17362.0  1755.508709
2590  user_198         Delhi  Tamil Nadu                56125.0  1755.487173
171   user_118         Delhi  Tamil Nadu                49613.0  1755.164402

In [67]:
print("===== Travel Speed Analysis =====")

loginDF["TimeDifferenceHours"] = (
    loginDF["TimeDifferenceMinutes"] / 60
)

loginDF["TravelSpeedKMH"] = np.where(
    loginDF["TimeDifferenceHours"] > 0,
    loginDF["DistanceKM"] / loginDF["TimeDifferenceHours"],
    0
)

travelSpeedDF = loginDF[
    loginDF["DistanceKM"].notna() &
    (loginDF["TimeDifferenceMinutes"] > 0)
].copy()

print(
    travelSpeedDF["TravelSpeedKMH"].describe()
)

===== Travel Speed Analysis =====
count     1066.000000
mean       154.736756
std       3125.835758
min          0.000042
25%          0.243523
50%          1.081665
75%          3.353280
max      95210.052879
Name: TravelSpeedKMH, dtype: float64

In [68]:
print("\n===== Highest Travel Speeds =====")

print(
    travelSpeedDF[
        [
            "UserName",
            "PreviousState",
            "State",
            "TimeDifferenceMinutes",
            "DistanceKM",
            "TravelSpeedKMH"
        ]
    ]
    .sort_values(
        "TravelSpeedKMH",
        ascending=False
    )
    .head(20)
)

===== Highest Travel Speeds =====
      UserName  PreviousState          State  TimeDifferenceMinutes  \
1664  user_954      Karnataka  Uttar Pradesh                    1.0
2655  user_954          Delhi  Uttar Pradesh                    1.0
1848  user_954  Uttar Pradesh          Delhi                    1.0
84    user_999      Telangana          Delhi                    8.0
1256  user_155     Tamil Nadu          Delhi                   28.0
37     user_37      Karnataka    Maharashtra                   44.0
46    user_285    Maharashtra    West Bengal                  163.0
685    user_55          Delhi    Maharashtra                  342.0
1399   user_60    Maharashtra      Telangana                  217.0
2727   user_83          Delhi    West Bengal                  593.0
1925  user_954          Delhi          Delhi                    1.0
1585  user_195          Delhi      Karnataka                  921.0
1264  user_954  Uttar Pradesh  Uttar Pradesh                    1.0
130   user_179    West Bengal      Karnataka                 1105.0
232    user_75    Maharashtra      Karnataka                  538.0
1558  user_294    Maharashtra      Karnataka                  536.0
1959   user_98      Karnataka      Telangana                  383.0
839   user_292          Delhi     Tamil Nadu                 1649.0
409   user_181     Tamil Nadu    West Bengal                 1282.0
385    user_98          Delhi      Karnataka                 1719.0

       DistanceKM  TravelSpeedKMH
1664  1586.834215    95210.052879
2655   419.275388    25156.523285
1848   417.963199    25077.791920
84    1258.378515     9437.838859
1256  1753.701325     3757.931410
37     730.770680      996.505473
46    1653.809504      608.764235
685   1150.691162      201.875642
1399   618.542212      171.025496
2727  1303.078724      131.846077
1925     1.950652      117.039103
1585  1736.773191      113.144833
1264     1.697356      101.841344
130   1560.171716       84.715206
232    737.962274       82.300625
1558   733.596982       82.119065
1959   501.597440       78.579233
839   1756.651277       63.916966
409   1360.998678       63.697286
385   1741.240399       60.776279

In [69]:
print("===== Login Time Distribution =====")

loginDF["LoginHour"] = loginDF["LoginTime"].dt.hour

print(
    loginDF["LoginHour"]
    .value_counts()
    .sort_index()
)

===== Login Time Distribution =====
LoginHour
0     71
1     48
2     50
3     67
4     51
5     49
6     69
7     43
8     60
9     60
10    71
11    71
12    58
13    49
14    57
15    46
16    61
17    60
18    53
19    59
20    51
21    53
22    60
23    62
Name: count, dtype: int64

In [70]:
print("\n===== Login Hour Statistics =====")

print(
    loginDF["LoginHour"].describe()
)

===== Login Hour Statistics =====
count    1379.000000
mean       11.453952
std         6.928613
min         0.000000
25%         6.000000
50%        11.000000
75%        17.000000
max        23.000000
Name: LoginHour, dtype: float64

In [17]:
print("===== City-State Relationship =====")

cityStateDF = (
    authLogsDF
    .groupby("State")["City"]
    .nunique()
    .reset_index(name="UniqueCityCount")
    .sort_values("UniqueCityCount", ascending=False)
)

print(cityStateDF)

===== City-State Relationship =====
           State  UniqueCityCount
2    Maharashtra                2
0          Delhi                1
1      Karnataka                1
3     Tamil Nadu                1
4      Telangana                1
5  Uttar Pradesh                1
6    West Bengal                1

In [18]:
print("\n===== City-State Combinations =====")

cityStateComboDF = (
    authLogsDF[
        ["State", "City"]
    ]
    .drop_duplicates()
    .sort_values(["State", "City"])
)

print(cityStateComboDF)

===== City-State Combinations =====
            State       City
2           Delhi      Delhi
5       Karnataka  Bengaluru
1     Maharashtra     Mumbai
4     Maharashtra       Pune
26     Tamil Nadu    Chennai
3       Telangana  Hyderabad
13  Uttar Pradesh    Lucknow
0     West Bengal    Kolkata

In [57]:
print("===== Feature Engineering =====")

# --------------------------------------------------
# 1. Prepare Login Data
# --------------------------------------------------

loginDF = authLogsDF[
    authLogsDF["EventName"] == "Login"
].copy()

loginDF["LoginTime"] = pd.to_datetime(
    loginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

loginDF = loginDF.sort_values(
    ["UserName", "LoginTime"]
).reset_index(drop=True)


# --------------------------------------------------
# 2. Previous Login Information
# --------------------------------------------------

loginDF["PreviousLoginTime"] = (
    loginDF.groupby("UserName")["LoginTime"]
    .shift(1)
)

loginDF["PreviousIP"] = (
    loginDF.groupby("UserName")["IPAddress"]
    .shift(1)
)

loginDF["PreviousBrowser"] = (
    loginDF.groupby("UserName")["BrowserID"]
    .shift(1)
)

loginDF["PreviousDevice"] = (
    loginDF.groupby("UserName")["device fingerprinting"]
    .shift(1)
)

loginDF["PreviousState"] = (
    loginDF.groupby("UserName")["State"]
    .shift(1)
)


# --------------------------------------------------
# 3. Time Features
# --------------------------------------------------

loginDF["TimeDifferenceMinutes"] = (
    loginDF["LoginTime"] -
    loginDF["PreviousLoginTime"]
).dt.total_seconds() / 60

loginDF["LoginHour"] = loginDF["LoginTime"].dt.hour

loginDF["IsNightLogin"] = (
    (loginDF["LoginHour"] < 6) |
    (loginDF["LoginHour"] >= 22)
).astype(int)


# --------------------------------------------------
# 4. Behavior Change Features
# --------------------------------------------------

loginDF["IPChanged"] = (
    loginDF["IPAddress"] != loginDF["PreviousIP"]
).astype(int)

loginDF["BrowserChanged"] = (
    loginDF["BrowserID"] != loginDF["PreviousBrowser"]
).astype(int)

loginDF["DeviceChanged"] = (
    loginDF["device fingerprinting"] !=
    loginDF["PreviousDevice"]
).astype(int)

loginDF["StateChanged"] = (
    loginDF["State"] != loginDF["PreviousState"]
).astype(int)

# First login has no previous login
firstLogin = loginDF["PreviousLoginTime"].isna()

changeColumns = [
    "IPChanged",
    "BrowserChanged",
    "DeviceChanged",
    "StateChanged"
]

loginDF.loc[firstLogin, changeColumns] = 0


# --------------------------------------------------
# 5. Distance Between Previous and Current Login
# --------------------------------------------------

R = 6371

lat1 = np.radians(
    loginDF.groupby("UserName")["Latitude"].shift(1)
)

lon1 = np.radians(
    loginDF.groupby("UserName")["Longitude"].shift(1)
)

lat2 = np.radians(loginDF["Latitude"])
lon2 = np.radians(loginDF["Longitude"])

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    np.sin(dlat / 2) ** 2
    +
    np.cos(lat1)
    * np.cos(lat2)
    * np.sin(dlon / 2) ** 2
)

c = 2 * np.arctan2(
    np.sqrt(a),
    np.sqrt(1 - a)
)

loginDF["DistanceKM"] = R * c

loginDF.loc[firstLogin, "DistanceKM"] = 0


# --------------------------------------------------
# 6. Travel Speed
# --------------------------------------------------

loginDF["TimeDifferenceHours"] = (
    loginDF["TimeDifferenceMinutes"] / 60
)

loginDF["TravelSpeedKMH"] = np.where(
    loginDF["TimeDifferenceHours"] > 0,
    loginDF["DistanceKM"] /
    loginDF["TimeDifferenceHours"],
    0
)

loginDF.loc[firstLogin, "TravelSpeedKMH"] = 0


# --------------------------------------------------
# 7. Current Login Security Features
# --------------------------------------------------

loginDF["LoginFailure"] = (
    loginDF["EventType"] == "Failure"
).astype(int)

loginDF["LoginWarning"] = (
    loginDF["EventType"] == "Warning"
).astype(int)

loginDF["LoginAlertFlag"] = (
    loginDF["LoginAlert"] == "Yes"
).astype(int)

loginDF["GeoFencingDisabled"] = (
    loginDF["WithGeoFencing"] == "No"
).astype(int)

loginDF["UnknownDevice"] = (
    loginDF["RememberDevice"] == "No"
).astype(int)

loginDF["VPNFlag"] = (
    loginDF["IsVPN"] == "Yes"
).astype(int)

loginDF["ProxyFlag"] = (
    loginDF["IsProxy"] == "Yes"
).astype(int)


# --------------------------------------------------
# 8. User History
# --------------------------------------------------

loginDF["PreviousLoginCount"] = (
    loginDF.groupby("UserName")
    .cumcount()
)

loginDF["IsNewIP"] = (
    ~loginDF.duplicated(
        ["UserName", "IPAddress"],
        keep="first"
    )
).astype(int)

loginDF["IsNewBrowser"] = (
    ~loginDF.duplicated(
        ["UserName", "BrowserID"],
        keep="first"
    )
).astype(int)

loginDF["IsNewDevice"] = (
    ~loginDF.duplicated(
        ["UserName", "device fingerprinting"],
        keep="first"
    )
).astype(int)


# --------------------------------------------------
# 9. Select Final ML Features
# --------------------------------------------------

featureColumns = [
    "TimeDifferenceMinutes",
    "LoginHour",
    "IsNightLogin",

    "IPChanged",
    "BrowserChanged",
    "DeviceChanged",
    "StateChanged",

    "DistanceKM",
    "TravelSpeedKMH",

    "LoginFailure",
    "LoginWarning",
    "LoginAlertFlag",
    "GeoFencingDisabled",
    "UnknownDevice",
    "VPNFlag",
    "ProxyFlag",
    "IPReputationScore",

    "PreviousLoginCount",
    "IsNewIP",
    "IsNewBrowser",
    "IsNewDevice"
]


# --------------------------------------------------
# 10. Create ML Dataset
# --------------------------------------------------

mlFeaturesDF = loginDF[
    ["UserName", "LoginTime"] + featureColumns
].copy()


# --------------------------------------------------
# 11. Handle NaN / Infinite Values
# --------------------------------------------------

mlFeaturesDF[featureColumns] = (
    mlFeaturesDF[featureColumns]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


print("\n===== Feature Engineering Completed =====")

print("Original Logs:", len(authLogsDF))
print("Login Observations:", len(mlFeaturesDF))
print("Number of ML Features:", len(featureColumns))

print("\nML Dataset Shape:")
print(mlFeaturesDF.shape)

print("\nFeature Columns:")
print(featureColumns)

print("\nFirst 5 Rows:")
display(mlFeaturesDF.head())

===== Feature Engineering =====

===== Feature Engineering Completed =====
Original Logs: 3000
Login Observations: 1379
Number of ML Features: 21

ML Dataset Shape:
(1379, 23)

Feature Columns:
['TimeDifferenceMinutes', 'LoginHour', 'IsNightLogin', 'IPChanged', 'BrowserChanged', 'DeviceChanged', 'StateChanged', 'DistanceKM', 'TravelSpeedKMH', 'LoginFailure', 'LoginWarning', 'LoginAlertFlag', 'GeoFencingDisabled', 'UnknownDevice', 'VPNFlag', 'ProxyFlag', 'IPReputationScore', 'PreviousLoginCount', 'IsNewIP', 'IsNewBrowser', 'IsNewDevice']

First 5 Rows:

,UserName,LoginTime,TimeDifferenceMinutes,LoginHour,IsNightLogin,IPChanged,BrowserChanged,DeviceChanged,StateChanged,DistanceKM,...,LoginAlertFlag,GeoFencingDisabled,UnknownDevice,VPNFlag,ProxyFlag,IPReputationScore,PreviousLoginCount,IsNewIP,IsNewBrowser,IsNewDevice
0,user_0,2026-07-12 10:00:00,0.0,10,0,0,0,0,0,0.000000,...,0,1,1,0,0,80,0,1,1,1
1,user_1,2026-07-12 10:01:00,0.0,10,0,0,0,0,0,0.000000,...,0,1,1,0,0,78,0,1,1,1
2,user_1,2026-07-17 15:27:00,7526.0,15,0,1,1,1,1,289.779181,...,1,1,1,0,0,97,1,1,1,1
3,user_1,2026-08-08 10:50:00,31403.0,10,0,1,1,1,1,501.600241,...,1,0,0,0,0,95,2,1,1,1
4,user_1,2026-09-04 05:28:00,38558.0,5,1,0,0,0,0,0.606627,...,1,1,0,0,0,73,3,0,0,0

In [58]:
print("===== Feature Quality Check =====")

X = mlFeaturesDF[featureColumns].copy()

print("Shape:", X.shape)

print("\nMissing Values:")
print(X.isnull().sum().sum())

print("\nInfinite Values:")
print(np.isinf(X).sum().sum())

print("\nData Types:")
print(X.dtypes.value_counts())

print("\nConstant Features:")
constantFeatures = [
    col for col in X.columns
    if X[col].nunique() <= 1
]

print(constantFeatures)

print("\nFeature Statistics:")
display(X.describe().T)

===== Feature Quality Check =====
Shape: (1379, 21)

Missing Values:
0

Infinite Values:
0

Data Types:
int64      17
float64     3
int32       1
Name: count, dtype: int64

Constant Features:
[]

Feature Statistics:

,count,mean,std,min,25%,50%,75%,max
TimeDifferenceMinutes,1379.0,68530.984046,105037.459220,0.0,1699.000000,24809.000000,79534.500000,595091.000000
LoginHour,1379.0,11.453952,6.928613,0.0,6.000000,11.000000,17.000000,23.000000
IsNightLogin,1379.0,0.332125,0.471146,0.0,0.000000,0.000000,1.000000,1.000000
IPChanged,1379.0,0.430022,0.495258,0.0,0.000000,0.000000,1.000000,1.000000
BrowserChanged,1379.0,0.330674,0.470627,0.0,0.000000,0.000000,1.000000,1.000000
DeviceChanged,1379.0,0.300943,0.458834,0.0,0.000000,0.000000,1.000000,1.000000
StateChanged,1379.0,0.646846,0.478124,0.0,0.000000,1.000000,1.000000,1.000000
DistanceKM,1379.0,716.386055,621.775047,0.0,1.711148,734.751083,1195.171406,1759.129952
TravelSpeedKMH,1379.0,119.615215,2748.762442,0.0,0.001245,0.469187,2.221514,95210.052879
LoginFailure,1379.0,0.260334,0.438976,0.0,0.000000,0.000000,1.000000,1.000000
LoginWarning,1379.0,0.159536,0.366308,0.0,0.000000,0.000000,0.000000,1.000000
LoginAlertFlag,1379.0,0.328499,0.469838,0.0,0.000000,0.000000,1.000000,1.000000
GeoFencingDisabled,1379.0,0.357505,0.479439,0.0,0.000000,0.000000,1.000000,1.000000
UnknownDevice,1379.0,0.399565,0.489987,0.0,0.000000,0.000000,1.000000,1.000000
VPNFlag,1379.0,0.066715,0.249618,0.0,0.000000,0.000000,0.000000,1.000000
ProxyFlag,1379.0,0.042785,0.202445,0.0,0.000000,0.000000,0.000000,1.000000
IPReputationScore,1379.0,80.596809,15.026629,21.0,75.000000,83.000000,91.000000,99.000000
PreviousLoginCount,1379.0,2.478608,2.321747,0.0,1.000000,2.000000,4.000000,15.000000
IsNewIP,1379.0,0.493836,0.500143,0.0,0.000000,0.000000,1.000000,1.000000
IsNewBrowser,1379.0,0.416244,0.493114,0.0,0.000000,0.000000,1.000000,1.000000
IsNewDevice,1379.0,0.413343,0.492612,0.0,0.000000,0.000000,1.000000,1.000000

In [59]:
print("===== Feature Correlation Analysis =====")

correlationDF = X.corr()

print(
    correlationDF.round(2)
)

===== Feature Correlation Analysis =====
                       TimeDifferenceMinutes  LoginHour  IsNightLogin  \
TimeDifferenceMinutes                   1.00       0.02         -0.03
LoginHour                               0.02       1.00         -0.38
IsNightLogin                           -0.03      -0.38          1.00
IPChanged                               0.22       0.00         -0.02
BrowserChanged                          0.17      -0.04          0.01
DeviceChanged                           0.16      -0.02          0.02
StateChanged                            0.26       0.01         -0.02
DistanceKM                              0.22       0.03          0.00
TravelSpeedKMH                         -0.03      -0.01         -0.03
LoginFailure                           -0.01      -0.02         -0.04
LoginWarning                            0.03      -0.00          0.05
LoginAlertFlag                         -0.04       0.00          0.04
GeoFencingDisabled                     -0.01       0.03         -0.01
UnknownDevice                          -0.02      -0.00         -0.00
VPNFlag                                 0.02      -0.04          0.02
ProxyFlag                               0.02      -0.02          0.02
IPReputationScore                       0.00       0.05         -0.01
PreviousLoginCount                     -0.12       0.00          0.02
IsNewIP                                -0.04      -0.02          0.02
IsNewBrowser                           -0.11      -0.02          0.02
IsNewDevice                            -0.12      -0.01          0.03

                       IPChanged  BrowserChanged  DeviceChanged  StateChanged  \
TimeDifferenceMinutes       0.22            0.17           0.16          0.26
LoginHour                   0.00           -0.04          -0.02          0.01
IsNightLogin               -0.02            0.01           0.02         -0.02
IPChanged                   1.00            0.35           0.35          0.35
BrowserChanged              0.35            1.00           0.40          0.29
DeviceChanged               0.35            0.40           1.00          0.28
StateChanged                0.35            0.29           0.28          1.00
DistanceKM                  0.28            0.22           0.22          0.84
TravelSpeedKMH             -0.03           -0.02          -0.01          0.03
LoginFailure               -0.06           -0.03          -0.03         -0.05
LoginWarning                0.06            0.04           0.05          0.07
LoginAlertFlag             -0.09           -0.04          -0.08         -0.10
GeoFencingDisabled         -0.07           -0.08          -0.05         -0.12
UnknownDevice              -0.03           -0.03          -0.06         -0.03
VPNFlag                     0.01           -0.01          -0.00         -0.03
ProxyFlag                  -0.01           -0.00           0.01          0.04
IPReputationScore           0.01           -0.00          -0.01         -0.02
PreviousLoginCount          0.26            0.22           0.16          0.40
IsNewIP                     0.23           -0.06          -0.05         -0.38
IsNewBrowser               -0.14            0.23          -0.02         -0.44
IsNewDevice                -0.16           -0.06           0.28         -0.45

                       DistanceKM  TravelSpeedKMH  LoginFailure  ...  \
TimeDifferenceMinutes        0.22           -0.03         -0.01  ...
LoginHour                    0.03           -0.01         -0.02  ...
IsNightLogin                 0.00           -0.03         -0.04  ...
IPChanged                    0.28           -0.03         -0.06  ...
BrowserChanged               0.22           -0.02         -0.03  ...
DeviceChanged                0.22           -0.01         -0.03  ...
StateChanged                 0.84            0.03         -0.05  ...
DistanceKM                   1.00            0.03         -0.06  ...
TravelSpeedKMH               0.03            1.00          0.06  ...
LoginFailure                -0.06            0.06          1.00  ...
LoginWarning                 0.08           -0.02         -0.26  ...
LoginAlertFlag              -0.09           -0.03          0.00  ...
GeoFencingDisabled          -0.10            0.06          0.10  ...
UnknownDevice               -0.01            0.05          0.08  ...
VPNFlag                     -0.06            0.03          0.03  ...
ProxyFlag                   -0.01           -0.01         -0.04  ...
IPReputationScore            0.02           -0.04          0.02  ...
PreviousLoginCount           0.35           -0.01         -0.09  ...
IsNewIP                     -0.34           -0.04          0.05  ...
IsNewBrowser                -0.39           -0.03          0.09  ...
IsNewDevice                 -0.39           -0.02          0.07  ...

                       LoginAlertFlag  GeoFencingDisabled  UnknownDevice  \
TimeDifferenceMinutes           -0.04               -0.01          -0.02
LoginHour                        0.00                0.03          -0.00
IsNightLogin                     0.04               -0.01          -0.00
IPChanged                       -0.09               -0.07          -0.03
BrowserChanged                  -0.04               -0.08          -0.03
DeviceChanged                   -0.08               -0.05          -0.06
StateChanged                    -0.10               -0.12          -0.03
DistanceKM                      -0.09               -0.10          -0.01
TravelSpeedKMH                  -0.03                0.06           0.05
LoginFailure                     0.00                0.10           0.08
LoginWarning                    -0.00               -0.09          -0.03
LoginAlertFlag                   1.00                0.07           0.04
GeoFencingDisabled               0.07                1.00           0.15
UnknownDevice                    0.04                0.15           1.00
VPNFlag                          0.04                0.02           0.00
ProxyFlag                       -0.04                0.01          -0.02
IPReputationScore                0.00                0.01           0.05
PreviousLoginCount              -0.09               -0.12          -0.07
IsNewIP                          0.06                0.07           0.06
IsNewBrowser                     0.06                0.11           0.07
IsNewDevice                      0.05                0.08           0.04

                       VPNFlag  ProxyFlag  IPReputationScore  \
TimeDifferenceMinutes     0.02       0.02               0.00
LoginHour                -0.04      -0.02               0.05
IsNightLogin              0.02       0.02              -0.01
IPChanged                 0.01      -0.01               0.01
BrowserChanged           -0.01      -0.00              -0.00
DeviceChanged            -0.00       0.01              -0.01
StateChanged             -0.03       0.04              -0.02
DistanceKM               -0.06      -0.01               0.02
TravelSpeedKMH            0.03      -0.01              -0.04
LoginFailure              0.03      -0.04               0.02
LoginWarning             -0.04      -0.02               0.03
LoginAlertFlag            0.04      -0.04               0.00
GeoFencingDisabled        0.02       0.01               0.01
UnknownDevice             0.00      -0.02               0.05
VPNFlag                   1.00       0.02              -0.60
ProxyFlag                 0.02       1.00              -0.50
IPReputationScore        -0.60      -0.50               1.00
PreviousLoginCount       -0.01       0.08              -0.05
IsNewIP                   0.03      -0.05               0.03
IsNewBrowser              0.02      -0.05               0.01
IsNewDevice              -0.00      -0.04               0.01

                       PreviousLoginCount  IsNewIP  IsNewBrowser  IsNewDevice
TimeDifferenceMinutes               -0.12    -0.04         -0.11        -0.12
LoginHour                            0.00    -0.02         -0.02        -0.01
IsNightLogin                         0.02     0.02          0.02         0.03
IPChanged                            0.26     0.23         -0.14        -0.16
BrowserChanged                       0.22    -0.06          0.23        -0.06
DeviceChanged                        0.16    -0.05         -0.02         0.28
StateChanged                         0.40    -0.38         -0.44        -0.45
DistanceKM                           0.35    -0.34         -0.39        -0.39
TravelSpeedKMH                      -0.01    -0.04         -0.03        -0.02
LoginFailure                        -0.09     0.05          0.09         0.07
LoginWarning                         0.07    -0.05         -0.04        -0.05
LoginAlertFlag                      -0.09     0.06          0.06         0.05
GeoFencingDisabled                  -0.12     0.07          0.11         0.08
UnknownDevice                       -0.07     0.06          0.07         0.04
VPNFlag                             -0.01     0.03          0.02        -0.00
ProxyFlag                            0.08    -0.05         -0.05        -0.04
IPReputationScore                   -0.05     0.03          0.01         0.01
PreviousLoginCount                   1.00    -0.48         -0.51        -0.49
IsNewIP                             -0.48     1.00          0.59         0.57
IsNewBrowser                        -0.51     0.59          1.00         0.67
IsNewDevice                         -0.49     0.57          0.67         1.00

[21 rows x 21 columns]

In [60]:
highCorrelation = (
    correlationDF
    .where(
        np.triu(
            np.ones(correlationDF.shape),
            k=1
        ).astype(bool)
    )
    .stack()
    .reset_index()
)

highCorrelation.columns = [
    "Feature1",
    "Feature2",
    "Correlation"
]

highCorrelation = highCorrelation[
    highCorrelation["Correlation"].abs() >= 0.80
].sort_values(
    "Correlation",
    key=lambda x: x.abs(),
    ascending=False
)

print("\n===== Highly Correlated Features =====")
print(highCorrelation)

===== Highly Correlated Features =====
         Feature1    Feature2  Correlation
105  StateChanged  DistanceKM     0.839196

In [61]:
print("===== Model Preparation =====")

# Only ML features
X = mlFeaturesDF[featureColumns].copy()

print("X Shape:", X.shape)

print("\nData Types:")
print(X.dtypes)

print("\nMissing Values:", X.isnull().sum().sum())

print("\nInfinite Values:", np.isinf(X).sum().sum())

print("\nFirst 5 Rows:")
display(X.head())

===== Model Preparation =====
X Shape: (1379, 21)

Data Types:
TimeDifferenceMinutes    float64
LoginHour                  int32
IsNightLogin               int64
IPChanged                  int64
BrowserChanged             int64
DeviceChanged              int64
StateChanged               int64
DistanceKM               float64
TravelSpeedKMH           float64
LoginFailure               int64
LoginWarning               int64
LoginAlertFlag             int64
GeoFencingDisabled         int64
UnknownDevice              int64
VPNFlag                    int64
ProxyFlag                  int64
IPReputationScore          int64
PreviousLoginCount         int64
IsNewIP                    int64
IsNewBrowser               int64
IsNewDevice                int64
dtype: object

Missing Values: 0

Infinite Values: 0

First 5 Rows:

,TimeDifferenceMinutes,LoginHour,IsNightLogin,IPChanged,BrowserChanged,DeviceChanged,StateChanged,DistanceKM,TravelSpeedKMH,LoginFailure,...,LoginAlertFlag,GeoFencingDisabled,UnknownDevice,VPNFlag,ProxyFlag,IPReputationScore,PreviousLoginCount,IsNewIP,IsNewBrowser,IsNewDevice
0,0.0,10,0,0,0,0,0,0.000000,0.000000,1,...,0,1,1,0,0,80,0,1,1,1
1,0.0,10,0,0,0,0,0,0.000000,0.000000,1,...,0,1,1,0,0,78,0,1,1,1
2,7526.0,15,0,1,1,1,1,289.779181,2.310225,0,...,1,1,1,0,0,97,1,1,1,1
3,31403.0,10,0,1,1,1,1,501.600241,0.958380,1,...,1,0,0,0,0,95,2,1,1,1
4,38558.0,5,1,0,0,0,0,0.606627,0.000944,0,...,1,1,0,0,0,73,3,0,0,0

In [62]:
print("===== Isolation Forest Training =====")

model = IsolationForest(
    n_estimators=200,
    contamination=0.05,
    random_state=42
)

model.fit(X)

print("Model training completed.")

===== Isolation Forest Training =====
Model training completed.

In [63]:
print("===== Model Prediction =====")

mlFeaturesDF["Prediction"] = model.predict(X)

print(
    mlFeaturesDF[
        ["UserName", "LoginTime", "Prediction"]
    ].head(20)
)

===== Model Prediction =====
    UserName           LoginTime  Prediction
0     user_0 2026-07-12 10:00:00           1
1     user_1 2026-07-12 10:01:00           1
2     user_1 2026-07-17 15:27:00           1
3     user_1 2026-08-08 10:50:00           1
4     user_1 2026-09-04 05:28:00           1
5     user_1 2026-11-21 06:54:00           1
6     user_1 2026-12-22 13:04:00           1
7     user_1 2027-02-14 00:27:00           1
8     user_1 2027-03-07 13:44:00           1
9     user_1 2027-03-21 16:24:00           1
10   user_10 2026-07-12 10:10:00           1
11   user_10 2026-11-30 09:35:00           1
12   user_10 2026-12-21 03:45:00           1
13   user_10 2026-12-31 16:13:00           1
14   user_10 2027-01-05 04:34:00           1
15   user_10 2027-04-08 05:28:00           1
16  user_100 2027-02-23 00:40:00           1
17  user_101 2026-01-12 22:32:00           1
18  user_101 2026-04-30 20:48:00           1
19  user_101 2026-10-29 17:45:00           1

In [64]:
print("===== Prediction Distribution =====")

print(
    mlFeaturesDF["Prediction"]
    .value_counts()
)

predictionSummary = (
    mlFeaturesDF["Prediction"]
    .value_counts()
    .rename_axis("Prediction")
    .reset_index(name="Count")
    
)

predictionSummary["Percentage"] = (
    predictionSummary["Count"]
    / len(mlFeaturesDF)
    * 100
)

print(predictionSummary)

===== Prediction Distribution =====
Prediction
 1    1310
-1      69
Name: count, dtype: int64
   Prediction  Count  Percentage
0           1   1310   94.996374
1          -1     69    5.003626

In [65]:
print("===== Anomaly Score =====")

mlFeaturesDF["AnomalyScore"] = (
    model.decision_function(X)
)

print(
    mlFeaturesDF[
        [
            "UserName",
            "LoginTime",
            "Prediction",
            "AnomalyScore"
        ]
    ]
    .head(20)
)

===== Anomaly Score =====
    UserName           LoginTime  Prediction  AnomalyScore
0     user_0 2026-07-12 10:00:00           1      0.131203
1     user_1 2026-07-12 10:01:00           1      0.129846
2     user_1 2026-07-17 15:27:00           1      0.047079
3     user_1 2026-08-08 10:50:00           1      0.058297
4     user_1 2026-09-04 05:28:00           1      0.074490
5     user_1 2026-11-21 06:54:00           1      0.009607
6     user_1 2026-12-22 13:04:00           1      0.052668
7     user_1 2027-02-14 00:27:00           1      0.100532
8     user_1 2027-03-07 13:44:00           1      0.008124
9     user_1 2027-03-21 16:24:00           1      0.105981
10   user_10 2026-07-12 10:10:00           1      0.125925
11   user_10 2026-11-30 09:35:00           1      0.012149
12   user_10 2026-12-21 03:45:00           1      0.003207
13   user_10 2026-12-31 16:13:00           1      0.037277
14   user_10 2027-01-05 04:34:00           1      0.040321
15   user_10 2027-04-08 05:28:00           1      0.051007
16  user_100 2027-02-23 00:40:00           1      0.100771
17  user_101 2026-01-12 22:32:00           1      0.035836
18  user_101 2026-04-30 20:48:00           1      0.120398
19  user_101 2026-10-29 17:45:00           1      0.088764

In [66]:
print("===== Top Suspicious Login Anomalies =====")

suspiciousDF = (
    mlFeaturesDF[
        mlFeaturesDF["Prediction"] == -1
    ]
    .sort_values(
        "AnomalyScore",
        ascending=True
    )
)

print(
    suspiciousDF[
        [
            "UserName",
            "LoginTime",
            "AnomalyScore",
            "TimeDifferenceMinutes",
            "IPChanged",
            "BrowserChanged",
            "DeviceChanged",
            "StateChanged",
            "DistanceKM",
            "TravelSpeedKMH",
            "LoginFailure",
            "LoginAlertFlag",
            "GeoFencingDisabled",
            "UnknownDevice",
            
            
            ]
    ]
    .head(20)
)

===== Top Suspicious Login Anomalies =====
      UserName           LoginTime  AnomalyScore  TimeDifferenceMinutes  \
1204    user_7 2027-01-23 22:36:00     -0.062540               281549.0
178   user_138 2027-01-30 02:46:00     -0.052618                  654.0
971    user_30 2026-09-21 00:16:00     -0.044363               223659.0
1252   user_81 2026-06-19 23:52:00     -0.044216                59466.0
1378  user_999 2026-07-10 10:08:00     -0.041720                    8.0
1043    user_4 2027-04-07 13:52:00     -0.038265                19671.0
838   user_272 2026-09-14 22:39:00     -0.037319               118153.0
629   user_230 2027-03-19 01:07:00     -0.036764                81421.0
723   user_250 2027-03-14 02:13:00     -0.032297                 9315.0
226   user_146 2026-06-07 03:30:00     -0.031536                10185.0
191    user_14 2027-03-29 03:14:00     -0.030989                13656.0
1343  user_954 2026-07-11 09:04:00     -0.030958                    1.0
1020   user_37 2027-03-06 09:58:00     -0.030403                 4988.0
1296   user_88 2027-01-08 10:48:00     -0.030389               395793.0
1008   user_37 2026-02-16 07:25:00     -0.029023                   44.0
1255   user_81 2026-12-22 04:23:00     -0.028363                 8393.0
651   user_236 2026-09-19 13:06:00     -0.027171               295298.0
775   user_260 2027-01-16 00:09:00     -0.026680                51458.0
557   user_215 2026-11-10 02:20:00     -0.026193               235748.0
634   user_232 2026-06-09 21:05:00     -0.025155               104128.0

      IPChanged  BrowserChanged  DeviceChanged  StateChanged   DistanceKM  \
1204          0               0              0             0     3.831688
178           0               1              0             1   291.798934
971           1               1              0             0     0.338122
1252          0               1              1             0     1.882010
1378          1               1              0             1  1258.378515
1043          1               1              1             1   514.189127
838           0               1              1             1  1656.145145
629           1               1              0             0   117.146535
723           0               0              0             1  1253.928719
226           1               1              1             1  1529.632809
191           1               1              1             1  1175.948000
1343          0               0              0             1   419.275388
1020          0               0              0             0     5.735347
1296          1               0              1             0     3.920408
1008          1               1              1             1   730.770680
1255          1               0              0             0     3.577737
651           1               1              1             1  1656.217949
775           1               1              1             1  1303.678937
557           0               0              1             1   516.273076
634           0               1              1             0     4.072936

      TravelSpeedKMH  LoginFailure  LoginAlertFlag  GeoFencingDisabled  \
1204        0.000817             0               0                   1
178        26.770544             0               1                   0
971         0.000091             0               1                   1
1252        0.001899             1               0                   0
1378     9437.838859             0               0                   1
1043        1.568367             0               1                   0
838         0.841017             0               1                   0
629         0.086327             1               1                   0
723         8.076836             0               1                   0
226         9.011092             0               1                   1
191         5.166731             1               0                   0
1343    25156.523285             1               0                   1
1020        0.068990             1               1                   1
1296        0.000594             0               0                   1
1008      996.505473             0               1                   0
1255        0.025577             0               0                   1
651         0.336518             1               0                   1
775         1.520089             1               0                   0
557         0.131396             1               0                   1
634         0.002347             0               0                   1

      UnknownDevice
1204              1
178               0
971               0
1252              1
1378              1
1043              0
838               1
629               1
723               1
226               0
191               1
1343              1
1020              1
1296              1
1008              0
1255              0
651               1
775               1
557               0
634               0

In [67]:
print("===== Anomaly Validation =====")

validationDF = mlFeaturesDF[
    mlFeaturesDF["Prediction"] == -1
].copy()

# Independent suspicious signals

validationDF["ImpossibleTravel"] = (
    (validationDF["DistanceKM"] >= 500) &
    (validationDF["TimeDifferenceMinutes"] <= 60)
).astype(int)

validationDF["MultipleChanges"] = (
    validationDF[
        [
            "IPChanged",
            "BrowserChanged",
            "DeviceChanged",
            "StateChanged"
        ]
    ].sum(axis=1) >= 2
).astype(int)

validationDF["FailedLoginUnknownDevice"] = (
    (validationDF["LoginFailure"] == 1) &
    (validationDF["UnknownDevice"] == 1)
).astype(int)

validationDF["NetworkRisk"] = (
    (
        (validationDF["VPNFlag"] == 1) |
        (validationDF["ProxyFlag"] == 1)
    ) &
    (validationDF["IPReputationScore"] < 50)
).astype(int)

validationDF["AlertSignal"] = (
    validationDF["LoginAlertFlag"] == 1
).astype(int)


# Count suspicious signals
validationDF["SuspiciousSignalCount"] = (
    validationDF[
        [
            "ImpossibleTravel",
            "MultipleChanges",
            "FailedLoginUnknownDevice",
            "NetworkRisk",
            "AlertSignal"
        ]
    ].sum(axis=1)
)


print("Total Model Anomalies:", len(validationDF))

print("\n===== Validation Summary =====")

print(
    validationDF["SuspiciousSignalCount"]
    .value_counts()
    .sort_index()
)

print("\n===== Signal Coverage =====")

print(
    validationDF[
        [
            "ImpossibleTravel",
            "MultipleChanges",
            "FailedLoginUnknownDevice",
            "NetworkRisk",
            "AlertSignal"
        ]
    ].sum()
)

===== Anomaly Validation =====
Total Model Anomalies: 69

===== Validation Summary =====
SuspiciousSignalCount
0     1
1    13
2    38
3    17
Name: count, dtype: int64

===== Signal Coverage =====
ImpossibleTravel             2
MultipleChanges             55
FailedLoginUnknownDevice    17
NetworkRisk                 34
AlertSignal                 32
dtype: int64

In [68]:
print("===== Risk Categorization =====")

riskDF = mlFeaturesDF.copy()

# --------------------------------------------------
# 1. Calculate Suspicious Signals
# --------------------------------------------------

riskDF["ImpossibleTravel"] = (
    (riskDF["DistanceKM"] >= 500) &
    (riskDF["TimeDifferenceMinutes"] <= 60)
).astype(int)

riskDF["MultipleChanges"] = (
    riskDF[
        [
            "IPChanged",
            "BrowserChanged",
            "DeviceChanged",
            "StateChanged"
        ]
    ].sum(axis=1) >= 2
).astype(int)

riskDF["FailedLoginUnknownDevice"] = (
    (riskDF["LoginFailure"] == 1) &
    (riskDF["UnknownDevice"] == 1)
).astype(int)

riskDF["NetworkRisk"] = (
    (
        (riskDF["VPNFlag"] == 1) |
        (riskDF["ProxyFlag"] == 1)
    ) &
    (riskDF["IPReputationScore"] < 50)
).astype(int)

riskDF["AlertSignal"] = (
    riskDF["LoginAlertFlag"] == 1
).astype(int)


# --------------------------------------------------
# 2. Total Suspicious Signals
# --------------------------------------------------

riskDF["SuspiciousSignalCount"] = (
    riskDF[
        [
            "ImpossibleTravel",
            "MultipleChanges",
            "FailedLoginUnknownDevice",
            "NetworkRisk",
            "AlertSignal"
        ]
    ].sum(axis=1)
)


# --------------------------------------------------
# 3. Risk Level
# --------------------------------------------------

riskDF["RiskLevel"] = np.select(
    [
        (riskDF["Prediction"] == -1) &
        (riskDF["SuspiciousSignalCount"] >= 3),

        (riskDF["Prediction"] == -1) &
        (riskDF["SuspiciousSignalCount"] >= 2),

        (riskDF["Prediction"] == -1) &
        (riskDF["SuspiciousSignalCount"] >= 1)
    ],
    [
        "High",
        "Medium",
        "Low"
    ],
    default="Normal"
)


# --------------------------------------------------
# 4. Summary
# --------------------------------------------------

print("\n===== Risk Level Distribution =====")

print(
    riskDF["RiskLevel"]
    .value_counts()
)


# --------------------------------------------------
# 5. Suspicious Login Report
# --------------------------------------------------

suspiciousReportDF = (
    riskDF[
        riskDF["RiskLevel"] != "Normal"
    ]
    .sort_values(
        ["RiskLevel", "AnomalyScore"],
        ascending=[True, True]
    )
)

print("\n===== Suspicious Login Report =====")

print(
    suspiciousReportDF[
        [
            "UserName",
            "LoginTime",
            "Prediction",
            "AnomalyScore",
            "SuspiciousSignalCount",
            "RiskLevel",
            "DistanceKM",
            "TravelSpeedKMH",
            "IPChanged",
            "BrowserChanged",
            "DeviceChanged",
            "StateChanged",
            "LoginFailure",
            "LoginAlertFlag",
           
        ]
    ]
    .head(20)
)

===== Risk Categorization =====

===== Risk Level Distribution =====
RiskLevel
Normal    1311
Medium      38
High        17
Low         13
Name: count, dtype: int64

===== Suspicious Login Report =====
      UserName           LoginTime  Prediction  AnomalyScore  \
178   user_138 2027-01-30 02:46:00          -1     -0.052618
971    user_30 2026-09-21 00:16:00          -1     -0.044363
1378  user_999 2026-07-10 10:08:00          -1     -0.041720
838   user_272 2026-09-14 22:39:00          -1     -0.037319
629   user_230 2027-03-19 01:07:00          -1     -0.036764
226   user_146 2026-06-07 03:30:00          -1     -0.031536
191    user_14 2027-03-29 03:14:00          -1     -0.030989
1008   user_37 2026-02-16 07:25:00          -1     -0.029023
651   user_236 2026-09-19 13:06:00          -1     -0.027171
775   user_260 2027-01-16 00:09:00          -1     -0.026680
763   user_257 2027-03-20 11:58:00          -1     -0.020192
665   user_238 2027-02-18 03:53:00          -1     -0.020156
919    user_29 2027-02-19 22:31:00          -1     -0.018121
93    user_119 2027-02-08 02:24:00          -1     -0.014663
544   user_211 2027-01-19 05:04:00          -1     -0.012513
317   user_162 2027-03-31 00:23:00          -1     -0.010700
62     user_11 2026-09-15 03:08:00          -1     -0.001192
1204    user_7 2027-01-23 22:36:00          -1     -0.062540
1255   user_81 2026-12-22 04:23:00          -1     -0.028363
634   user_232 2026-06-09 21:05:00          -1     -0.025155

      SuspiciousSignalCount RiskLevel   DistanceKM  TravelSpeedKMH  IPChanged  \
178                       3      High   291.798934       26.770544          0
971                       3      High     0.338122        0.000091          1
1378                      3      High  1258.378515     9437.838859          1
838                       3      High  1656.145145        0.841017          0
629                       3      High   117.146535        0.086327          1
226                       3      High  1529.632809        9.011092          1
191                       3      High  1175.948000        5.166731          1
1008                      3      High   730.770680      996.505473          1
651                       3      High  1656.217949        0.336518          1
775                       3      High  1303.678937        1.520089          1
763                       3      High   287.064025        1.425697          1
665                       3      High  1184.728076        5.092319          0
919                       3      High   846.056218        0.714484          0
93                        3      High   418.604114        0.140723          1
544                       3      High  1176.257921       10.546246          0
317                       3      High  1149.496147        1.761500          1
62                        3      High  1198.089090        0.771492          0
1204                      1       Low     3.831688        0.000817          0
1255                      1       Low     3.577737        0.025577          1
634                       1       Low     4.072936        0.002347          0

      BrowserChanged  DeviceChanged  StateChanged  LoginFailure  \
178                1              0             1             0
971                1              0             0             0
1378               1              0             1             0
838                1              1             1             0
629                1              0             0             1
226                1              1             1             0
191                1              1             1             1
1008               1              1             1             0
651                1              1             1             1
775                1              1             1             1
763                0              1             1             0
665                0              1             1             0
919                0              1             1             0
93                 0              0             1             1
544                0              0             1             1
317                0              0             1             0
62                 0              1             1             0
1204               0              0             0             0
1255               0              0             0             0
634                1              1             0             0

      LoginAlertFlag
178                1
971                1
1378               0
838                1
629                1
226                1
191                0
1008               1
651                0
775                0
763                1
665                1
919                1
93                 1
544                1
317                1
62                 1
1204               0
1255               0
634                0

In [69]:
riskDF["RiskLevel"] = np.select(
    [
        (riskDF["Prediction"] == -1) &
        (riskDF["SuspiciousSignalCount"] >= 3),

        (riskDF["Prediction"] == -1) &
        (riskDF["SuspiciousSignalCount"] >= 2),

        (riskDF["Prediction"] == -1)
    ],
    [
        "High",
        "Medium",
        "Low"
    ],
    default="Normal"
)

In [70]:
print("===== Updated Risk Level Distribution =====")

print(
    riskDF["RiskLevel"].value_counts()
)

===== Updated Risk Level Distribution =====
RiskLevel
Normal    1310
Medium      38
High        17
Low         14
Name: count, dtype: int64

In [71]:
print(
    riskDF[
        riskDF["Prediction"] == -1
    ]["RiskLevel"]
    .value_counts()
)

RiskLevel
Medium    38
High      17
Low       14
Name: count, dtype: int64

In [72]:
print("===== Final Suspicious Login Report =====")

# Create reason column
riskDF["Reason"] = ""

riskDF.loc[
    riskDF["ImpossibleTravel"] == 1,
    "Reason"
] += "Impossible Travel; "

riskDF.loc[
    riskDF["IPChanged"] == 1,
    "Reason"
] += "IP Changed; "

riskDF.loc[
    riskDF["BrowserChanged"] == 1,
    "Reason"
] += "Browser Changed; "

riskDF.loc[
    riskDF["DeviceChanged"] == 1,
    "Reason"
] += "Device Changed; "

riskDF.loc[
    riskDF["StateChanged"] == 1,
    "Reason"
] += "State Changed; "

riskDF.loc[
    riskDF["LoginFailure"] == 1,
    "Reason"
] += "Login Failure; "

riskDF.loc[
    riskDF["LoginAlertFlag"] == 1,
    "Reason"
] += "Login Alert; "

riskDF.loc[
    riskDF["GeoFencingDisabled"] == 1,
    "Reason"
] += "Geo-Fencing Disabled; "

riskDF.loc[
    riskDF["UnknownDevice"] == 1,
    "Reason"
] += "Unknown Device; "

riskDF.loc[
    riskDF["VPNFlag"] == 1,
    "Reason"
] += "VPN Detected; "

riskDF.loc[
    riskDF["ProxyFlag"] == 1,
    "Reason"
] += "Proxy Detected; "

riskDF.loc[
    riskDF["IPReputationScore"] < 50,
    "Reason"
] += "Low IP Reputation; "


# Only suspicious logins
finalSuspiciousDF = (
    riskDF[
        riskDF["RiskLevel"] != "Normal"
    ]
    .copy()
)


# Sort:
# High → Medium → Low
riskOrder = {
    "High": 1,
    "Medium": 2,
    "Low": 3
}

finalSuspiciousDF["RiskOrder"] = (
    finalSuspiciousDF["RiskLevel"]
    .map(riskOrder)
)

finalSuspiciousDF = (
    finalSuspiciousDF
    .sort_values(
        ["RiskOrder", "AnomalyScore"],
        ascending=[True, True]
    )
    .drop(columns="RiskOrder")
)


# Final columns
finalSuspiciousDF = finalSuspiciousDF[
    [
        "UserName",
        "LoginTime",
        "RiskLevel",
        "AnomalyScore",
        "SuspiciousSignalCount",
        "DistanceKM",
        "TravelSpeedKMH",
        "IPChanged",
        "BrowserChanged",
        "DeviceChanged",
        "StateChanged",
        "LoginFailure",
        "LoginAlertFlag",
        "VPNFlag",
        "ProxyFlag",
        "IPReputationScore",
        "Reason"
    ]
]


print("Total Suspicious Logins:", len(finalSuspiciousDF))

print("\n===== Final Report =====")

display(
    finalSuspiciousDF.head(20)
)

===== Final Suspicious Login Report =====
Total Suspicious Logins: 69

===== Final Report =====

,UserName,LoginTime,RiskLevel,AnomalyScore,SuspiciousSignalCount,DistanceKM,TravelSpeedKMH,IPChanged,BrowserChanged,DeviceChanged,StateChanged,LoginFailure,LoginAlertFlag,VPNFlag,ProxyFlag,IPReputationScore,Reason
178,user_138,2027-01-30 02:46:00,High,-0.052618,3,291.798934,26.770544,0,1,0,1,0,1,1,1,24,Browser Changed; State Changed; Login Alert; V...
971,user_30,2026-09-21 00:16:00,High,-0.044363,3,0.338122,0.000091,1,1,0,0,0,1,1,0,39,IP Changed; Browser Changed; Login Alert; Geo-...
1378,user_999,2026-07-10 10:08:00,High,-0.041720,3,1258.378515,9437.838859,1,1,0,1,0,0,1,0,45,Impossible Travel; IP Changed; Browser Changed...
838,user_272,2026-09-14 22:39:00,High,-0.037319,3,1656.145145,0.841017,0,1,1,1,0,1,0,1,42,Browser Changed; Device Changed; State Changed...
629,user_230,2027-03-19 01:07:00,High,-0.036764,3,117.146535,0.086327,1,1,0,0,1,1,1,0,51,IP Changed; Browser Changed; Login Failure; Lo...
226,user_146,2026-06-07 03:30:00,High,-0.031536,3,1529.632809,9.011092,1,1,1,1,0,1,1,0,26,IP Changed; Browser Changed; Device Changed; S...
191,user_14,2027-03-29 03:14:00,High,-0.030989,3,1175.948000,5.166731,1,1,1,1,1,0,1,0,48,IP Changed; Browser Changed; Device Changed; S...
1008,user_37,2026-02-16 07:25:00,High,-0.029023,3,730.770680,996.505473,1,1,1,1,0,1,1,0,66,Impossible Travel; IP Changed; Browser Changed...
651,user_236,2026-09-19 13:06:00,High,-0.027171,3,1656.217949,0.336518,1,1,1,1,1,0,1,0,37,IP Changed; Browser Changed; Device Changed; S...
775,user_260,2027-01-16 00:09:00,High,-0.026680,3,1303.678937,1.520089,1,1,1,1,1,0,1,0,41,IP Changed; Browser Changed; Device Changed; S...
763,user_257,2027-03-20 11:58:00,High,-0.020192,3,287.064025,1.425697,1,0,1,1,0,1,1,0,42,IP Changed; Device Changed; State Changed; Log...
665,user_238,2027-02-18 03:53:00,High,-0.020156,3,1184.728076,5.092319,0,0,1,1,0,1,0,1,32,Device Changed; State Changed; Login Alert; Un...
919,user_29,2027-02-19 22:31:00,High,-0.018121,3,846.056218,0.714484,0,0,1,1,0,1,0,1,44,Device Changed; State Changed; Login Alert; Un...
93,user_119,2027-02-08 02:24:00,High,-0.014663,3,418.604114,0.140723,1,0,0,1,1,1,0,1,47,IP Changed; State Changed; Login Failure; Logi...
544,user_211,2027-01-19 05:04:00,High,-0.012513,3,1176.257921,10.546246,0,0,0,1,1,1,1,0,38,State Changed; Login Failure; Login Alert; Geo...
317,user_162,2027-03-31 00:23:00,High,-0.010700,3,1149.496147,1.761500,1,0,0,1,0,1,1,0,34,IP Changed; State Changed; Login Alert; Geo-Fe...
62,user_11,2026-09-15 03:08:00,High,-0.001192,3,1198.089090,0.771492,0,0,1,1,0,1,1,0,36,Device Changed; State Changed; Login Alert; VP...
1252,user_81,2026-06-19 23:52:00,Medium,-0.044216,2,1.882010,0.001899,0,1,1,0,1,0,0,1,62,Browser Changed; Device Changed; Login Failure...
1043,user_4,2027-04-07 13:52:00,Medium,-0.038265,2,514.189127,1.568367,1,1,1,1,0,1,0,1,50,IP Changed; Browser Changed; Device Changed; S...
723,user_250,2027-03-14 02:13:00,Medium,-0.032297,2,1253.928719,8.076836,0,0,0,1,0,1,1,1,47,State Changed; Login Alert; Unknown Device; VP...

In [73]:
print("===== FINAL MODEL EVALUATION SUMMARY =====")

totalLogins = len(riskDF)
normalCount = (riskDF["RiskLevel"] == "Normal").sum()
lowCount = (riskDF["RiskLevel"] == "Low").sum()
mediumCount = (riskDF["RiskLevel"] == "Medium").sum()
highCount = (riskDF["RiskLevel"] == "High").sum()

print("Total Login Events:", totalLogins)
print("Normal Logins:", normalCount)
print("Low Risk:", lowCount)
print("Medium Risk:", mediumCount)
print("High Risk:", highCount)

print("\n===== Percentages =====")

print(
    f"Normal: {(normalCount / totalLogins) * 100:.2f}%"
)

print(
    f"Low Risk: {(lowCount / totalLogins) * 100:.2f}%"
)

print(
    f"Medium Risk: {(mediumCount / totalLogins) * 100:.2f}%"
)

print(
    f"High Risk: {(highCount / totalLogins) * 100:.2f}%"
)

print("\n===== ML Anomaly Summary =====")

anomalyCount = (riskDF["Prediction"] == -1).sum()

print("Total Anomalies:", anomalyCount)
print(
    "Anomaly Percentage:",
    round((anomalyCount / totalLogins) * 100, 2),
    "%"
)

print("\n===== Validation Summary =====")

validatedAnomalies = (
    riskDF[
        (riskDF["Prediction"] == -1) &
        (riskDF["SuspiciousSignalCount"] >= 1)
    ]
    .shape[0]
)

print(
    "Anomalies with Suspicious Signals:",
    validatedAnomalies
)

print(
    "Validation Coverage:",
    round(
        (validatedAnomalies / anomalyCount) * 100,
        2
    ),
    "%"
)

===== FINAL MODEL EVALUATION SUMMARY =====
Total Login Events: 1379
Normal Logins: 1310
Low Risk: 14
Medium Risk: 38
High Risk: 17

===== Percentages =====
Normal: 95.00%
Low Risk: 1.02%
Medium Risk: 2.76%
High Risk: 1.23%

===== ML Anomaly Summary =====
Total Anomalies: 69
Anomaly Percentage: 5.0 %

===== Validation Summary =====
Anomalies with Suspicious Signals: 68
Validation Coverage: 98.55 %

In [74]:
print("===== Exporting Final Suspicious Login Report =====")

outputFile = "Final_Suspicious_Login_Report.csv"

finalSuspiciousDF.to_csv(
    outputFile,
    index=False
)

print("File saved successfully:", outputFile)
print("Total records:", len(finalSuspiciousDF))

===== Exporting Final Suspicious Login Report =====
File saved successfully: Final_Suspicious_Login_Report.csv
Total records: 69

In [75]:
print("===== Loading Unseen Test Data =====")

testDF = pd.read_csv(
    (r"C:\Users\rishu\Downloads\unseen_login_test_data.csv")
)

print("Test Data Shape:", testDF.shape)

print("\nColumns:")
print(testDF.columns.tolist())

print("\nActual Label Distribution:")
print(testDF["ActualLabel"].value_counts())

print("\nFirst 5 Rows:")
display(testDF.head())

===== Loading Unseen Test Data =====
Test Data Shape: (500, 40)

Columns:
['UserName', 'TimeStamp', 'EventName', 'EventType', 'IPAddress', 'BrowserID', 'device fingerprinting', 'State', 'City', 'Latitude', 'Longitude', 'LoginAlert', 'WithGeoFencing', 'RememberDevice', 'IsVPN', 'IsProxy', 'IPReputationScore', 'UserId', 'EmailId', 'MobileNo', 'Country', 'Lang', 'Location', 'EventID', 'AuthType', 'MultiFactorType', 'OTPType', 'OTPSendOn', 'Reason', 'ServiceId', 'ServiceName', 'ServiceState', 'SessionID', 'TokenID', 'UId', 'UserAgent', 'departmentName', 'serviceGroupId', 'month', 'ActualLabel']

Actual Label Distribution:
ActualLabel
0    449
1     51
Name: count, dtype: int64

First 5 Rows:

,UserName,TimeStamp,EventName,EventType,IPAddress,BrowserID,device fingerprinting,State,City,Latitude,...,ServiceName,ServiceState,SessionID,TokenID,UId,UserAgent,departmentName,serviceGroupId,month,ActualLabel
0,user_529,01-05-2027 03:49,Login,Success,10.198.171.237,Firefox,device_60,West Bengal,Hyderabad,27.427180,...,Finance,Active,sess_5001,token_5001,529,Firefox UserAgent,Sales,3,5,0
1,user_260,01-05-2027 04:41,Login,Success,10.244.180.95,Firefox,device_11,Karnataka,Kolkata,19.060260,...,HRMS,Active,sess_5002,token_5002,260,Firefox UserAgent,IT,3,5,0
2,user_229,01-05-2027 05:18,Login,Success,10.153.108.160,Safari,device_188,Delhi,Lucknow,13.418408,...,CRM,Active,sess_5003,token_5003,229,Safari UserAgent,Sales,2,5,0
3,user_322,01-05-2027 07:08,Login,Success,10.207.94.129,Safari,device_205,Uttar Pradesh,Hyderabad,17.779510,...,CRM,Active,sess_5004,token_5004,322,Safari UserAgent,Sales,2,5,0
4,user_597,01-05-2027 10:02,Login,Success,10.12.188.125,Chrome,device_232,Tamil Nadu,Chennai,8.746206,...,Portal,Active,sess_5005,token_5005,597,Chrome UserAgent,Sales,4,5,0

In [76]:
print("===== Feature Engineering on Unseen Data =====")

# --------------------------------------------------
# 1. Prepare Login Data
# --------------------------------------------------

testLoginDF = testDF[
    testDF["EventName"] == "Login"
].copy()

testLoginDF["LoginTime"] = pd.to_datetime(
    testLoginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

testLoginDF = testLoginDF.sort_values(
    ["UserName", "LoginTime"]
).reset_index(drop=True)


# --------------------------------------------------
# 2. Previous Login Information
# --------------------------------------------------

testLoginDF["PreviousLoginTime"] = (
    testLoginDF.groupby("UserName")["LoginTime"]
    .shift(1)
)

testLoginDF["PreviousIP"] = (
    testLoginDF.groupby("UserName")["IPAddress"]
    .shift(1)
)

testLoginDF["PreviousBrowser"] = (
    testLoginDF.groupby("UserName")["BrowserID"]
    .shift(1)
)

testLoginDF["PreviousDevice"] = (
    testLoginDF.groupby("UserName")["device fingerprinting"]
    .shift(1)
)

testLoginDF["PreviousState"] = (
    testLoginDF.groupby("UserName")["State"]
    .shift(1)
)


# --------------------------------------------------
# 3. Time Features
# --------------------------------------------------

testLoginDF["TimeDifferenceMinutes"] = (
    testLoginDF["LoginTime"]
    - testLoginDF["PreviousLoginTime"]
).dt.total_seconds() / 60

testLoginDF["LoginHour"] = (
    testLoginDF["LoginTime"].dt.hour
)

testLoginDF["IsNightLogin"] = (
    (testLoginDF["LoginHour"] < 6) |
    (testLoginDF["LoginHour"] >= 22)
).astype(int)


# --------------------------------------------------
# 4. Behavior Change Features
# --------------------------------------------------

testLoginDF["IPChanged"] = (
    testLoginDF["IPAddress"] !=
    testLoginDF["PreviousIP"]
).astype(int)

testLoginDF["BrowserChanged"] = (
    testLoginDF["BrowserID"] !=
    testLoginDF["PreviousBrowser"]
).astype(int)

testLoginDF["DeviceChanged"] = (
    testLoginDF["device fingerprinting"] !=
    testLoginDF["PreviousDevice"]
).astype(int)

testLoginDF["StateChanged"] = (
    testLoginDF["State"] !=
    testLoginDF["PreviousState"]
).astype(int)


# First login of each user has no previous login
firstLogin = (
    testLoginDF["PreviousLoginTime"].isna()
)

changeColumns = [
    "IPChanged",
    "BrowserChanged",
    "DeviceChanged",
    "StateChanged"
]

testLoginDF.loc[
    firstLogin,
    changeColumns
] = 0


# --------------------------------------------------
# 5. Distance
# --------------------------------------------------

R = 6371

lat1 = np.radians(
    testLoginDF.groupby("UserName")["Latitude"].shift(1)
)

lon1 = np.radians(
    testLoginDF.groupby("UserName")["Longitude"].shift(1)
)

lat2 = np.radians(
    testLoginDF["Latitude"]
)

lon2 = np.radians(
    testLoginDF["Longitude"]
)

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    np.sin(dlat / 2) ** 2
    +
    np.cos(lat1)
    * np.cos(lat2)
    * np.sin(dlon / 2) ** 2
)

c = 2 * np.arctan2(
    np.sqrt(a),
    np.sqrt(1 - a)
)

testLoginDF["DistanceKM"] = R * c

testLoginDF.loc[
    firstLogin,
    "DistanceKM"
] = 0


# --------------------------------------------------
# 6. Travel Speed
# --------------------------------------------------

testLoginDF["TimeDifferenceHours"] = (
    testLoginDF["TimeDifferenceMinutes"] / 60
)

testLoginDF["TravelSpeedKMH"] = np.where(
    testLoginDF["TimeDifferenceHours"] > 0,
    testLoginDF["DistanceKM"] /
    testLoginDF["TimeDifferenceHours"],
    0
)

testLoginDF.loc[
    firstLogin,
    "TravelSpeedKMH"
] = 0


# --------------------------------------------------
# 7. Security Features
# --------------------------------------------------

testLoginDF["LoginFailure"] = (
    testLoginDF["EventType"] == "Failure"
).astype(int)

testLoginDF["LoginWarning"] = (
    testLoginDF["EventType"] == "Warning"
).astype(int)

testLoginDF["LoginAlertFlag"] = (
    testLoginDF["LoginAlert"] == "Yes"
).astype(int)

testLoginDF["GeoFencingDisabled"] = (
    testLoginDF["WithGeoFencing"] == "No"
).astype(int)

testLoginDF["UnknownDevice"] = (
    testLoginDF["RememberDevice"] == "No"
).astype(int)

testLoginDF["VPNFlag"] = (
    testLoginDF["IsVPN"] == "Yes"
).astype(int)

testLoginDF["ProxyFlag"] = (
    testLoginDF["IsProxy"] == "Yes"
).astype(int)


# --------------------------------------------------
# 8. User History
# --------------------------------------------------

testLoginDF["PreviousLoginCount"] = (
    testLoginDF.groupby("UserName")
    .cumcount()
)

testLoginDF["IsNewIP"] = (
    ~testLoginDF.duplicated(
        ["UserName", "IPAddress"],
        keep="first"
    )
).astype(int)

testLoginDF["IsNewBrowser"] = (
    ~testLoginDF.duplicated(
        ["UserName", "BrowserID"],
        keep="first"
    )
).astype(int)

testLoginDF["IsNewDevice"] = (
    ~testLoginDF.duplicated(
        ["UserName", "device fingerprinting"],
        keep="first"
    )
).astype(int)


# --------------------------------------------------
# 9. Create Test ML Dataset
# --------------------------------------------------

testMLDF = testLoginDF[
    ["UserName", "LoginTime", "ActualLabel"]
    + featureColumns
].copy()


# --------------------------------------------------
# 10. Clean Features
# --------------------------------------------------

testMLDF[featureColumns] = (
    testMLDF[featureColumns]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


print("\n===== Unseen Feature Engineering Completed =====")

print("Test Login Observations:", len(testMLDF))

print(
    "Number of ML Features:",
    len(featureColumns)
)

print(
    "\nTest ML Dataset Shape:",
    testMLDF.shape
)

print("\nFeature Columns:")
print(featureColumns)

print("\nFirst 5 Rows:")
display(testMLDF.head())

===== Feature Engineering on Unseen Data =====

===== Unseen Feature Engineering Completed =====
Test Login Observations: 500
Number of ML Features: 21

Test ML Dataset Shape: (500, 24)

Feature Columns:
['TimeDifferenceMinutes', 'LoginHour', 'IsNightLogin', 'IPChanged', 'BrowserChanged', 'DeviceChanged', 'StateChanged', 'DistanceKM', 'TravelSpeedKMH', 'LoginFailure', 'LoginWarning', 'LoginAlertFlag', 'GeoFencingDisabled', 'UnknownDevice', 'VPNFlag', 'ProxyFlag', 'IPReputationScore', 'PreviousLoginCount', 'IsNewIP', 'IsNewBrowser', 'IsNewDevice']

First 5 Rows:

,UserName,LoginTime,ActualLabel,TimeDifferenceMinutes,LoginHour,IsNightLogin,IPChanged,BrowserChanged,DeviceChanged,StateChanged,...,LoginAlertFlag,GeoFencingDisabled,UnknownDevice,VPNFlag,ProxyFlag,IPReputationScore,PreviousLoginCount,IsNewIP,IsNewBrowser,IsNewDevice
0,user_1,2027-05-27 19:16:00,0,0.0,19,0,0,0,0,0,...,0,0,0,0,0,82,0,1,1,1
1,user_10,2027-05-16 06:01:00,1,0.0,6,0,0,0,0,0,...,0,1,1,1,1,59,0,1,1,1
2,user_100,2027-05-23 19:07:00,0,0.0,19,0,0,0,0,0,...,0,0,0,0,0,88,0,1,1,1
3,user_104,2027-05-14 18:25:00,0,0.0,18,0,0,0,0,0,...,0,0,0,0,0,93,0,1,1,1
4,user_105,2027-05-20 20:34:00,0,0.0,20,0,0,0,0,0,...,0,0,0,0,0,79,0,1,1,1

In [77]:
print("===== Unseen Data Prediction =====")

# Only the 21 ML features
X_test = testMLDF[featureColumns].copy()

print("Test Feature Shape:", X_test.shape)

# Use the ALREADY TRAINED model
testMLDF["Prediction"] = model.predict(X_test)

print("\n===== Prediction Results =====")

print(
    testMLDF[
        [
            "UserName",
            "LoginTime",
            "Prediction"
        ]
    ].head(20)
)

===== Unseen Data Prediction =====
Test Feature Shape: (500, 21)

===== Prediction Results =====
    UserName           LoginTime  Prediction
0     user_1 2027-05-27 19:16:00           1
1    user_10 2027-05-16 06:01:00          -1
2   user_100 2027-05-23 19:07:00           1
3   user_104 2027-05-14 18:25:00           1
4   user_105 2027-05-20 20:34:00           1
5   user_106 2027-05-22 12:09:00           1
6   user_110 2027-05-03 16:15:00           1
7   user_110 2027-05-20 00:41:00           1
8   user_110 2027-05-23 02:34:00           1
9   user_112 2027-05-05 13:06:00           1
10  user_118 2027-05-27 18:00:00           1
11   user_12 2027-05-11 23:58:00           1
12  user_120 2027-05-23 14:24:00           1
13  user_121 2027-05-08 04:28:00           1
14  user_124 2027-05-06 23:56:00           1
15  user_125 2027-05-26 04:37:00           1
16  user_126 2027-05-07 16:51:00           1
17  user_126 2027-05-09 04:00:00           1
18  user_127 2027-05-19 04:19:00          -1
19  user_131 2027-05-17 09:31:00           1

In [78]:
print("\n===== Test Prediction Distribution =====")

print(
    testMLDF["Prediction"]
    .value_counts()
)

===== Test Prediction Distribution =====
Prediction
 1    486
-1     14
Name: count, dtype: int64

In [79]:
testPredictionSummary = (
    testMLDF["Prediction"]
    .value_counts()
    .rename_axis("Prediction")
    .reset_index(name="Count")
)

testPredictionSummary["Percentage"] = (
    testPredictionSummary["Count"]
    / len(testMLDF)
    * 100
)

print("\n===== Test Prediction Summary =====")

print(
    testPredictionSummary.round(2)
)

===== Test Prediction Summary =====
   Prediction  Count  Percentage
0           1    486        97.2
1          -1     14         2.8

In [80]:
print("===== Actual vs Predicted Labels =====")

# Convert ActualLabel to Isolation Forest format
# 0 = Normal  ->  1
# 1 = Anomaly -> -1

testMLDF["ActualPrediction"] = (
    testMLDF["ActualLabel"]
    .map({
        0: 1,
        1: -1
    })
)

comparisonDF = testMLDF[
    [
        "UserName",
        "LoginTime",
        "ActualLabel",
        "ActualPrediction",
        "Prediction"
    ]
].copy()

comparisonDF["Correct"] = (
    comparisonDF["ActualPrediction"]
    == comparisonDF["Prediction"]
)

print(comparisonDF.head(20))

print("\n===== Correct vs Incorrect =====")
print(
    comparisonDF["Correct"]
    .value_counts()
)

===== Actual vs Predicted Labels =====
    UserName           LoginTime  ActualLabel  ActualPrediction  Prediction  \
0     user_1 2027-05-27 19:16:00            0                 1           1
1    user_10 2027-05-16 06:01:00            1                -1          -1
2   user_100 2027-05-23 19:07:00            0                 1           1
3   user_104 2027-05-14 18:25:00            0                 1           1
4   user_105 2027-05-20 20:34:00            0                 1           1
5   user_106 2027-05-22 12:09:00            0                 1           1
6   user_110 2027-05-03 16:15:00            0                 1           1
7   user_110 2027-05-20 00:41:00            0                 1           1
8   user_110 2027-05-23 02:34:00            0                 1           1
9   user_112 2027-05-05 13:06:00            0                 1           1
10  user_118 2027-05-27 18:00:00            0                 1           1
11   user_12 2027-05-11 23:58:00            0                 1           1
12  user_120 2027-05-23 14:24:00            0                 1           1
13  user_121 2027-05-08 04:28:00            0                 1           1
14  user_124 2027-05-06 23:56:00            0                 1           1
15  user_125 2027-05-26 04:37:00            0                 1           1
16  user_126 2027-05-07 16:51:00            0                 1           1
17  user_126 2027-05-09 04:00:00            0                 1           1
18  user_127 2027-05-19 04:19:00            1                -1          -1
19  user_131 2027-05-17 09:31:00            0                 1           1

    Correct
0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True

===== Correct vs Incorrect =====
Correct
True     463
False     37
Name: count, dtype: int64

In [81]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("===== Model Evaluation on Unseen Data =====")

# Actual labels
y_true = testMLDF["ActualPrediction"]

# Model predictions
y_pred = testMLDF["Prediction"]


# --------------------------------------------------
# 1. Accuracy
# --------------------------------------------------

accuracy = accuracy_score(
    y_true,
    y_pred
)


# --------------------------------------------------
# 2. Precision
# --------------------------------------------------

precision = precision_score(
    y_true,
    y_pred,
    pos_label=-1
)


# --------------------------------------------------
# 3. Recall
# --------------------------------------------------

recall = recall_score(
    y_true,
    y_pred,
    pos_label=-1
)


# --------------------------------------------------
# 4. F1 Score
# --------------------------------------------------

f1 = f1_score(
    y_true,
    y_pred,
    pos_label=-1
)


# --------------------------------------------------
# 5. Print Metrics
# --------------------------------------------------

print("\n===== Performance Metrics =====")

print(
    "Accuracy :", round(accuracy * 100, 2), "%"
)

print(
    "Precision:", round(precision * 100, 2), "%"
)

print(
    "Recall   :", round(recall * 100, 2), "%"
)

print(
    "F1 Score :", round(f1 * 100, 2), "%"
)


# --------------------------------------------------
# 6. Confusion Matrix
# --------------------------------------------------

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=[1, -1]
)

print("\n===== Confusion Matrix =====")

print(
    pd.DataFrame(
        cm,
        index=["Actual Normal", "Actual Anomaly"],
        columns=["Predicted Normal", "Predicted Anomaly"]
    )
)


# --------------------------------------------------
# 7. Classification Report
# --------------------------------------------------

print("\n===== Classification Report =====")

print(
    classification_report(
        y_true,
        y_pred,
        labels=[1, -1],
        target_names=[
            "Normal",
            "Anomaly"
        ]
    )
)

===== Model Evaluation on Unseen Data =====

===== Performance Metrics =====
Accuracy : 92.6 %
Precision: 100.0 %
Recall   : 27.45 %
F1 Score : 43.08 %

===== Confusion Matrix =====
                Predicted Normal  Predicted Anomaly
Actual Normal                449                  0
Actual Anomaly                37                 14

===== Classification Report =====
              precision    recall  f1-score   support

      Normal       0.92      1.00      0.96       449
     Anomaly       1.00      0.27      0.43        51

    accuracy                           0.93       500
   macro avg       0.96      0.64      0.70       500
weighted avg       0.93      0.93      0.91       500

In [6]:

# Function to count values in a column
def count_single(column):
    return (
        authLogsDF
        .groupby(column)
        .size()
        .reset_index(name="count")
        .sort_values(by="count", ascending=False)
    )

# Function to filter data
def filter_by(condition):
    return authLogsDF.query(condition)

# List of columns
columns = [
    "City",
    "Country",
    "departmentName",
    "ServiceName",
    "month",
    "BrowserID",
    "MultiFactorType",
    "LoginAlert",
    "WithGeoFencing",
    "AuthType"
]

# Show counts for each column
for col_name in columns:
    print(f"\n====== {col_name} ======")
    print(count_single(col_name))

====== City ======
        City  count
2      Delhi    391
7       Pune    380
1    Chennai    378
0  Bengaluru    376
4    Kolkata    376
6     Mumbai    371
3  Hyderabad    364
5    Lucknow    364

====== Country ======
  Country  count
0   India   3000

====== departmentName ======
  departmentName  count
2             HR    567
0          Admin    502
5        Support    499
4          Sales    496
1        Finance    474
3             IT    462

====== ServiceName ======
  ServiceName  count
1         ERP    638
4     Payroll    603
0         CRM    597
3        HRMS    590
2     Finance    572

====== month ======
   month  count
11   Sep    314
8    May    293
4    Jan    267
6    Jun    264
7    Mar    264
10   Oct    257
5    Jul    248
9    Nov    248
1    Aug    245
0    Apr    219
3    Feb    217
2    Dec    164

====== BrowserID ======
      BrowserID  count
6   BROWSER_006    140
21  BROWSER_021    129
5   BROWSER_005    125
2   BROWSER_002    122
11  BROWSER_011    122
22  BROWSER_022    121
12  BROWSER_012    121
20  BROWSER_020    118
10  BROWSER_010    112
18  BROWSER_018    110
26  BROWSER_026    108
4   BROWSER_004    107
7   BROWSER_007    107
8   BROWSER_008    105
0   BROWSER_000    104
3   BROWSER_003    101
25  BROWSER_025     99
28  BROWSER_028     98
19  BROWSER_019     96
24  BROWSER_024     95
17  BROWSER_017     94
9   BROWSER_009     92
13  BROWSER_013     87
23  BROWSER_023     83
14  BROWSER_014     81
27  BROWSER_027     79
16  BROWSER_016     67
15  BROWSER_015     64
1   BROWSER_001     64
29  BROWSER_029     49

====== MultiFactorType ======
     MultiFactorType  count
1              Email    868
2                SMS    836
0  Authenticator App    803

====== LoginAlert ======
  LoginAlert  count
0         No   1747
1        Yes   1253

====== WithGeoFencing ======
  WithGeoFencing  count
1            Yes   1664
0             No   1336

====== AuthType ======
    AuthType  count
0  Biometric    819
1      OAuth    736
2   Password    733
3        SSO    712

pandas.core.frame.DataFrame

In [8]:
# Success events
print(filter_by("EventType == 'Success'"))

# Delhi records
print(filter_by("City == 'Delhi'"))

# Geo-fencing disabled
print(filter_by("WithGeoFencing == 'No'"))

       AuthType BrowserID       City Country               EmailId EventID  \
0     Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2     Biometric  BR771088    Lucknow   India   user_84@example.com  EV1002
4     Biometric  BR899550  Bengaluru   India  user_260@example.com  EV1004
5     Biometric  BR559381    Chennai   India  user_103@example.com  EV1005
7         OAuth  BR161483  Bengaluru   India  user_247@example.com  EV1007
...         ...       ...        ...     ...                   ...     ...
2044  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2045  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2046  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2047  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2048  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000

             EventName EventType        IPAddress Lang  ...       UId  \
0               Logout   Success   27.174.190.229   en  ...  UID46421
2       Account Unlock   Success   84.216.197.199   en  ...  UID44438
4               Logout   Success  200.237.136.236   en  ...  UID82063
5       Account Unlock   Success      64.58.17.87   en  ...  UID63354
7               Logout   Success   253.100.68.238   hi  ...  UID34356
...                ...       ...              ...  ...  ...       ...
2044  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2045  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2046  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2047  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2048  OTP Verification   Success  240.240.240.240   en  ...  UID46421

           UserAgent  UserId  UserName WithGeoFencing departmentName  \
0       Edge/Windows    4527   user_58             No             HR
2       Safari/macOS    7543   user_84             No             IT
4       Edge/Windows    5342  user_260             No             IT
5       Edge/Windows    2545  user_103            Yes        Support
7     Chrome/Windows    2113  user_247            Yes          Admin
...              ...     ...       ...            ...            ...
2044    Edge/Windows    4527  user_538             No             HR
2045    Edge/Windows    4527  user_817             No             HR
2046    Edge/Windows    4527  user_916             No             HR
2047    Edge/Windows    4527  user_327             No             HR
2048    Edge/Windows    4527  user_874             No             HR

     serviceGroupId month user fingerprinting device fingerprinting
0                 2   Sep     UF_F04E6876A972       DF_6999C7455347
2                 3   May     UF_2069C6387300       DF_00E46BA1B36D
4                 9   Feb     UF_BF79A9B844FF       DF_6DC595EC47BF
5                 7   May     UF_03C64C5B358D       DF_027D56EBFDD9
7                 2   Nov     UF_0E8AFC2842F6       DF_B1AFC725787E
...             ...   ...                 ...                   ...
2044              2   Sep     UF_E732C3C0F3BD       DF_6999C7455347
2045              2   Sep     UF_BCC2C4342A2D       DF_6999C7455347
2046              2   Sep     UF_C9F2038A7A98       DF_6999C7455347
2047              2   Sep     UF_037E2E9EBBE7       DF_6999C7455347
2048              2   Sep     UF_2220FB59601A       DF_6999C7455347

[1208 rows x 35 columns]
       AuthType BrowserID   City Country               EmailId EventID  \
0     Biometric  BR356787  Delhi   India   user_58@example.com  EV1000
9     Biometric  BR795613  Delhi   India  user_155@example.com  EV1009
11        OAuth  BR333238  Delhi   India  user_196@example.com  EV1011
16    Biometric  BR801364  Delhi   India  user_249@example.com  EV1016
18        OAuth  BR793655  Delhi   India   user_62@example.com  EV1018
...         ...       ...    ...     ...                   ...     ...
2044  Biometric  BR356787  Delhi   India   user_58@example.com  EV1000
2045  Biometric  BR356787  Delhi   India   user_58@example.com  EV1000
2046  Biometric  BR356787  Delhi   India   user_58@example.com  EV1000
2047  Biometric  BR356787  Delhi   India   user_58@example.com  EV1000
2048  Biometric  BR356787  Delhi   India   user_58@example.com  EV1000

             EventName EventType        IPAddress Lang  ...       UId  \
0               Logout   Success   27.174.190.229   en  ...  UID46421
9                Login   Warning     35.68.30.228   en  ...  UID44335
11              Logout   Failure    118.90.79.211   en  ...  UID66959
16    OTP Verification   Failure   216.120.236.33   en  ...  UID65255
18      Password Reset   Success     166.88.4.218   hi  ...  UID70910
...                ...       ...              ...  ...  ...       ...
2044  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2045  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2046  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2047  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2048  OTP Verification   Success  240.240.240.240   en  ...  UID46421

           UserAgent  UserId  UserName WithGeoFencing departmentName  \
0       Edge/Windows    4527   user_58             No             HR
9       Edge/Windows    8239  user_155             No          Sales
11    Chrome/Android    6139  user_196             No          Sales
16    Chrome/Android    2341  user_249             No             HR
18      Safari/macOS    6511   user_62            Yes          Admin
...              ...     ...       ...            ...            ...
2044    Edge/Windows    4527  user_538             No             HR
2045    Edge/Windows    4527  user_817             No             HR
2046    Edge/Windows    4527  user_916             No             HR
2047    Edge/Windows    4527  user_327             No             HR
2048    Edge/Windows    4527  user_874             No             HR

     serviceGroupId month user fingerprinting device fingerprinting
0                 2   Sep     UF_F04E6876A972       DF_6999C7455347
9                 1   Sep     UF_2DF794F72347       DF_34C13D39365E
11                9   Nov     UF_B7BBE64107FC       DF_B06299C86564
16                9   May     UF_EBF8DD0B3041       DF_81344204793C
18                6   May     UF_A70425350FC8       DF_12A82BA8ABE7
...             ...   ...                 ...                   ...
2044              2   Sep     UF_E732C3C0F3BD       DF_6999C7455347
2045              2   Sep     UF_BCC2C4342A2D       DF_6999C7455347
2046              2   Sep     UF_C9F2038A7A98       DF_6999C7455347
2047              2   Sep     UF_037E2E9EBBE7       DF_6999C7455347
2048              2   Sep     UF_2220FB59601A       DF_6999C7455347

[295 rows x 35 columns]
       AuthType BrowserID       City Country               EmailId EventID  \
0     Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2     Biometric  BR771088    Lucknow   India   user_84@example.com  EV1002
4     Biometric  BR899550  Bengaluru   India  user_260@example.com  EV1004
9     Biometric  BR795613      Delhi   India  user_155@example.com  EV1009
11        OAuth  BR333238      Delhi   India  user_196@example.com  EV1011
...         ...       ...        ...     ...                   ...     ...
2044  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2045  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2046  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2047  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000
2048  Biometric  BR356787      Delhi   India   user_58@example.com  EV1000

             EventName EventType        IPAddress Lang  ...       UId  \
0               Logout   Success   27.174.190.229   en  ...  UID46421
2       Account Unlock   Success   84.216.197.199   en  ...  UID44438
4               Logout   Success  200.237.136.236   en  ...  UID82063
9                Login   Warning     35.68.30.228   en  ...  UID44335
11              Logout   Failure    118.90.79.211   en  ...  UID66959
...                ...       ...              ...  ...  ...       ...
2044  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2045  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2046  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2047  OTP Verification   Success  240.240.240.240   en  ...  UID46421
2048  OTP Verification   Success  240.240.240.240   en  ...  UID46421

           UserAgent  UserId  UserName WithGeoFencing departmentName  \
0       Edge/Windows    4527   user_58             No             HR
2       Safari/macOS    7543   user_84             No             IT
4       Edge/Windows    5342  user_260             No             IT
9       Edge/Windows    8239  user_155             No          Sales
11    Chrome/Android    6139  user_196             No          Sales
...              ...     ...       ...            ...            ...
2044    Edge/Windows    4527  user_538             No             HR
2045    Edge/Windows    4527  user_817             No             HR
2046    Edge/Windows    4527  user_916             No             HR
2047    Edge/Windows    4527  user_327             No             HR
2048    Edge/Windows    4527  user_874             No             HR

     serviceGroupId month user fingerprinting device fingerprinting
0                 2   Sep     UF_F04E6876A972       DF_6999C7455347
2                 3   May     UF_2069C6387300       DF_00E46BA1B36D
4                 9   Feb     UF_BF79A9B844FF       DF_6DC595EC47BF
9                 1   Sep     UF_2DF794F72347       DF_34C13D39365E
11                9   Nov     UF_B7BBE64107FC       DF_B06299C86564
...             ...   ...                 ...                   ...
2044              2   Sep     UF_E732C3C0F3BD       DF_6999C7455347
2045              2   Sep     UF_BCC2C4342A2D       DF_6999C7455347
2046              2   Sep     UF_C9F2038A7A98       DF_6999C7455347
2047              2   Sep     UF_037E2E9EBBE7       DF_6999C7455347
2048              2   Sep     UF_2220FB59601A       DF_6999C7455347

[1077 rows x 35 columns]

In [9]:
print("Cleaned Logs")

# Create a copy of the original DataFrame
cleanedDF = authLogsDF.copy()

# Fill null values in specific columns
cleanedDF[["OTPType", "OTPSendOn", "MultiFactorType"]] = (
    cleanedDF[["OTPType", "OTPSendOn", "MultiFactorType"]]
    .fillna("Not Available")
)

# Display first 5 rows
cleanedDF.head()

Cleaned Logs

,AuthType,BrowserID,City,Country,EmailId,EventID,EventName,EventType,IPAddress,Lang,...,UId,UserAgent,UserId,UserName,WithGeoFencing,departmentName,serviceGroupId,month,user fingerprinting,device fingerprinting
0,Biometric,BR356787,Delhi,India,user_58@example.com,EV1000,Logout,Success,27.174.190.229,en,...,UID46421,Edge/Windows,4527,user_58,No,HR,2,Sep,UF_F04E6876A972,DF_6999C7455347
1,Biometric,BR733052,Mumbai,India,user_195@example.com,EV1001,Password Reset,Failure,187.118.138.32,hi,...,UID37460,Chrome/Android,2169,user_195,Yes,Sales,4,May,UF_642A37BC1AA8,DF_765B997FF461
2,Biometric,BR771088,Lucknow,India,user_84@example.com,EV1002,Account Unlock,Success,84.216.197.199,en,...,UID44438,Safari/macOS,7543,user_84,No,IT,3,May,UF_2069C6387300,DF_00E46BA1B36D
3,Password,BR214975,Lucknow,India,user_261@example.com,EV1003,Logout,Failure,203.175.109.153,en,...,UID75612,Edge/Windows,9317,user_261,Yes,Support,5,Feb,UF_115E80D696E8,DF_CDD62577CABF
4,Biometric,BR899550,Bengaluru,India,user_260@example.com,EV1004,Logout,Success,200.237.136.236,en,...,UID82063,Edge/Windows,5342,user_260,No,IT,9,Feb,UF_BF79A9B844FF,DF_6DC595EC47BF

In [10]:
print("Failed Logins")

# Count failed login attempts by user
riskyUserDF = (
    authLogsDF[authLogsDF["EventType"] == "Failure"]
    .groupby("UserName")
    .size()
    .reset_index(name="count")
    .sort_values(by="count", ascending=False)
)

# Display the result
print(riskyUserDF)

Failed Logins
     UserName  count
133  user_235      7
134  user_236      6
268  user_954      6
209   user_40      6
271   user_98      6
..        ...    ...
115  user_214      1
106  user_206      1
103  user_202      1
101  user_200      1
273  user_992      1

[274 rows x 2 columns]

In [11]:
print("Geo-Fencing Violation Detection")

# Geo-Fencing Violation Detection
geoFenceViolationDF = (
    authLogsDF[authLogsDF["WithGeoFencing"] == "No"]
    .groupby("UserName")
    .size()
    .reset_index(name="Count")
    .sort_values(by="Count", ascending=False)
)

print(geoFenceViolationDF)


print("\nRisk Analysis")

# Failed login records
failureDF = authLogsDF[authLogsDF["EventType"] == "Failure"].copy()

# Login Alert records
alertDF = authLogsDF[authLogsDF["LoginAlert"] == "Yes"].copy()


# Generic Risk Analysis Function
def risk_analysis(df, group_col):
    return (
        df.groupby(group_col)
        .size()
        .reset_index(name="Count")
        .sort_values(by="Count", ascending=False)
    )


print("\nFailures by Department")
print(risk_analysis(failureDF, "departmentName"))

print("\nLogin Alerts by Department")
print(risk_analysis(alertDF, "departmentName"))

print("\nFailures by Service")
print(risk_analysis(failureDF, "ServiceName"))

print("\nLogin Alerts by Service")
print(risk_analysis(alertDF, "ServiceName"))

print("\nFailures by IP Address")
print(risk_analysis(failureDF, "IPAddress"))

print("\nLogin Alerts by IP Address")
print(risk_analysis(alertDF, "IPAddress"))

Geo-Fencing Violation Detection
     UserName  Count
275   user_68     10
311   user_93     10
193  user_278      9
12    user_11      9
168  user_254      8
..        ...    ...
259  user_550      1
151  user_239      1
256  user_538      1
155  user_242      1
0      user_0      1

[321 rows x 2 columns]

Risk Analysis

Failures by Department
  departmentName  Count
2             HR    137
4          Sales    115
5        Support    115
3             IT    108
1        Finance    100
0          Admin     83

Login Alerts by Department
  departmentName  Count
2             HR    179
5        Support    175
0          Admin    174
4          Sales    161
3             IT    152
1        Finance    151

Failures by Service
  ServiceName  Count
1         ERP    160
4     Payroll    142
3        HRMS    136
0         CRM    118
2     Finance    102

Login Alerts by Service
  ServiceName  Count
0         CRM    218
3        HRMS    218
4     Payroll    189
1         ERP    185
2     Finance    182

Failures by IP Address
           IPAddress  Count
417  250.250.250.250     12
335  222.222.222.222      8
32   111.111.111.111      6
427  253.235.120.150      1
420    251.36.28.103      1
..               ...    ...
213    176.162.165.2      1
214   176.26.249.223      1
215    176.59.107.62      1
216  177.187.122.192      1
634     98.28.156.58      1

[635 rows x 2 columns]

Login Alerts by IP Address
          IPAddress  Count
0      1.184.97.188      1
666   252.20.46.243      1
653  25.171.110.129      1
654   25.244.209.49      1
655  250.161.156.92      1
..              ...    ...
335   18.136.238.97      1
336  18.157.162.182      1
337   18.163.23.139      1
338    18.187.99.99      1
991    99.89.198.68      1

[992 rows x 2 columns]

In [12]:
print("User Mobility Analysis: User logging from multiple cities, browsers, and IP addresses")

# Function to find users with multiple distinct values
def multi_location_users(column):
    result = (
        authLogsDF
        .groupby("UserName")[column]
        .nunique()
        .reset_index(name=f"No of {column}")
    )

    # Keep only users with more than one distinct value
    result = result[result[f"No of {column}"] > 1]

    return result.sort_values(by=f"No of {column}", ascending=False)


# Users logging from multiple cities
print("\nUsers logging from multiple cities")
print(multi_location_users("City"))

# Users using multiple browsers
print("\nUsers using multiple browsers")
print(multi_location_users("BrowserID"))

# Users logging from multiple IP addresses
print("\nUsers logging from multiple IP addresses")
print(multi_location_users("IPAddress"))

User Mobility Analysis: User logging from multiple cities, browsers, and IP addresses

Users logging from multiple cities
     UserName  No of City
47    user_14           8
237   user_37           8
54   user_146           8
256   user_49           8
254   user_47           7
..        ...         ...
28   user_122           2
168  user_249           2
165  user_246           2
31   user_125           2
328  user_999           2

[297 rows x 2 columns]

Users using multiple browsers
     UserName  No of BrowserID
237   user_37               16
181  user_260               14
95   user_183               14
164  user_245               13
283   user_68               13
..        ...              ...
220  user_296                2
28   user_122                2
143  user_226                2
24    user_12                2
46   user_139                2

[296 rows x 2 columns]

Users logging from multiple IP addresses
     UserName  No of IPAddress
237   user_37               16
95   user_183               14
181  user_260               14
283   user_68               13
164  user_245               13
..        ...              ...
24    user_12                2
40   user_133                2
220  user_296                2
46   user_139                2
328  user_999                2

[298 rows x 2 columns]

In [7]:
print("===== Multiple IP Changes Within Same Session =====")

sameSessionIPDF = (
    authLogsDF
    .groupby(["UserName", "SessionID"])
    .agg(
        DistinctIPs=("IPAddress", "nunique"),
        IPAddresses=("IPAddress", lambda x: list(set(x)))
    )
    .reset_index()
)

sameSessionIPDF = sameSessionIPDF[
    sameSessionIPDF["DistinctIPs"] > 1
]

print(sameSessionIPDF.sort_values("DistinctIPs", ascending=False))

===== Multiple IP Changes Within Same Session =====
      UserName  SessionID  DistinctIPs                      IPAddresses
1915  user_858  SID832052            3   [30.1.1.1, 30.1.1.2, 30.1.1.3]
1866   user_79  SID391773            2  [94.174.185.61, 52.100.125.108]
2039  user_999  SID832052            2             [10.1.1.1, 20.1.1.1]

In [10]:
print(authLogsDF["SessionID"])

0       SID832052
1       SID270555
2       SID881177
3       SID832052
4       SID234628
          ...
2044    SID832052
2045    SID832052
2046    SID832052
2047    SID832052
2048    SID832052
Name: SessionID, Length: 2049, dtype: object

In [19]:

print("===== Impossible Travel Detection =====")

# Filter successful login events
loginDF = authLogsDF[
    (authLogsDF["EventName"] == "Login") &
    (authLogsDF["EventType"] == "Success")
].copy()

# Convert timestamp to datetime
loginDF["LoginTime"] = pd.to_datetime(
    loginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

# Sort by User and Login Time
loginDF = loginDF.sort_values(["UserName", "LoginTime"])

# Previous login information
loginDF["PrevCity"] = loginDF.groupby("UserName")["City"].shift(1)
loginDF["PrevIP"] = loginDF.groupby("UserName")["IPAddress"].shift(1)
loginDF["PrevLoginTime"] = loginDF.groupby("UserName")["LoginTime"].shift(1)

# Time difference in minutes
loginDF["TimeDiffMinutes"] = (
    (loginDF["LoginTime"] - loginDF["PrevLoginTime"])
    .dt.total_seconds() / 60
)

# Keep records where city and IP both changed
impossibleTravelDF = loginDF[
    loginDF["PrevCity"].notna() &
    (loginDF["City"] != loginDF["PrevCity"]) &
    (loginDF["IPAddress"] != loginDF["PrevIP"])
].copy()

# Assign Risk Level
conditions = [
    impossibleTravelDF["TimeDiffMinutes"] <= 5,
    impossibleTravelDF["TimeDiffMinutes"] <= 15,
    impossibleTravelDF["TimeDiffMinutes"] <= 30
]

choices = ["Critical", "High", "Medium"]

impossibleTravelDF["RiskLevel"] = np.select(
    conditions,
    choices,
    default="Low"
)

# Remove Low Risk
impossibleTravelDF = impossibleTravelDF[
    impossibleTravelDF["RiskLevel"] != "Low"
]

# Risk Level ordering
risk_order = {
    "Critical": 1,
    "High": 2,
    "Medium": 3
}

impossibleTravelDF["RiskOrder"] = (
    impossibleTravelDF["RiskLevel"].map(risk_order)
)

# Select required columns
impossibleTravelDF = impossibleTravelDF[
    [
        "UserName",
        "PrevCity",
        "City",
        "PrevIP",
        "IPAddress",
        "PrevLoginTime",
        "LoginTime",
        "TimeDiffMinutes",
        "RiskLevel",
        "RiskOrder"
    ]
]

# Sort like Spark
impossibleTravelDF = (
    impossibleTravelDF
    .sort_values(
        by=["RiskOrder", "TimeDiffMinutes"],
        ascending=[True, True]
    )
    .drop(columns="RiskOrder")
)

# Display all columns and rows
print(impossibleTravelDF)

===== Impossible Travel Detection =====
      UserName PrevCity     City    PrevIP IPAddress       PrevLoginTime  \
2017  user_858    Delhi     Pune  30.1.1.1  30.1.1.2 2026-09-27 23:46:00
2018  user_858     Pune  Chennai  30.1.1.2  30.1.1.3 2026-09-27 23:46:00
2001  user_999    Delhi   Mumbai  10.1.1.1  20.1.1.1 2026-07-10 10:00:00

               LoginTime  TimeDiffMinutes RiskLevel
2017 2026-09-27 23:46:00              0.0  Critical
2018 2026-09-27 23:46:00              0.0  Critical
2001 2026-07-10 10:08:00              8.0      High

In [14]:
print("===== User Brute Force Detection =====")

# Filter failed login events
failedLoginDF = authLogsDF[
    (authLogsDF["EventName"] == "Login") &
    (authLogsDF["EventType"] == "Failure")
].copy()

# Convert timestamp
failedLoginDF["LoginTime"] = pd.to_datetime(
    failedLoginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

# Sort by User and LoginTime
failedLoginDF = failedLoginDF.sort_values(
    ["UserName", "LoginTime"]
)

# Count failed attempts within the previous 10 minutes
def failed_attempts(group):
    group = group.copy()

    group["FailedAttempts"] = (
        group.set_index("LoginTime")
             .rolling("10min")
             .count()["UserName"]
             .values
    )

    return group

userBruteForceDF = (
    failedLoginDF
    .groupby("UserName", group_keys=False)
    .apply(failed_attempts)
)

# Assign Risk Level
conditions = [
    userBruteForceDF["FailedAttempts"] >= 10,
    userBruteForceDF["FailedAttempts"] >= 5,
    userBruteForceDF["FailedAttempts"] >= 3
]

choices = [
    "Critical",
    "High",
    "Medium"
]

userBruteForceDF["RiskLevel"] = np.select(
    conditions,
    choices,
    default="Low"
)

# Keep High and Critical only (>=5 attempts)
userBruteForceDF = (
    userBruteForceDF[
        userBruteForceDF["FailedAttempts"] >= 5
    ][
        [
            "UserName",
            "IPAddress",
            "LoginTime",
            "FailedAttempts",
            "RiskLevel"
        ]
    ]
    .drop_duplicates()
)

print(userBruteForceDF)

===== User Brute Force Detection =====
      UserName        IPAddress           LoginTime  FailedAttempts RiskLevel
2006  user_954  111.111.111.111 2026-07-11 09:04:00             5.0      High
2007  user_954  111.111.111.111 2026-07-11 09:05:00             6.0      High

C:\Users\rishu\AppData\Local\Temp\ipykernel_11056\3038384137.py:37: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(failed_attempts)

In [6]:
print("===== Suspicious Browser/IP Change After Failure =====")


# Convert timestamp
mobilityDF = authLogsDF.copy()
mobilityDF["LoginTime"] = pd.to_datetime(
    mobilityDF["TimeStamp"],
    format="%d-%m-%Y %H:%M"
)

# Sort data
mobilityDF = mobilityDF.sort_values(["UserName", "LoginTime"])

# Previous values
mobilityDF["PrevBrowser"] = mobilityDF.groupby("UserName")["BrowserID"].shift(1)
mobilityDF["PrevIP"] = mobilityDF.groupby("UserName")["IPAddress"].shift(1)
mobilityDF["PrevEventType"] = mobilityDF.groupby("UserName")["EventType"].shift(1)
mobilityDF["PrevEventName"] = mobilityDF.groupby("UserName")["EventName"].shift(1)

# Suspicious pattern
browserChangeDF = mobilityDF[
    (mobilityDF["PrevEventType"] == "Failure") &
    (mobilityDF["EventType"] == "Success") &
    (mobilityDF["PrevEventName"] == "Login") &
    (mobilityDF["EventName"] == "Login") &
    (mobilityDF["BrowserID"] != mobilityDF["PrevBrowser"]) &
    (mobilityDF["IPAddress"] != mobilityDF["PrevIP"])
]

print(browserChangeDF[
    [
        "UserName",
        "PrevBrowser",
        "BrowserID",
        "PrevIP",
        "IPAddress",
        "LoginTime"
    ]
])

===== Suspicious Browser/IP Change After Failure =====
      UserName PrevBrowser BrowserID           PrevIP        IPAddress  \
850     user_1    BR356787  BR659236  250.250.250.250  180.224.252.113
958   user_160    BR996151  BR363175    43.123.193.58      115.3.69.51
1107  user_194    BR602270  BR484919    13.111.102.32    29.32.251.233
730   user_199    BR978214  BR412276   200.243.213.80    21.41.165.118
481   user_201    BR104492  BR240431    74.75.202.189    155.19.207.32
26    user_213    BR255365  BR960408   62.132.155.127   77.215.151.149
1026  user_236    BR471247  BR468790  184.238.234.178    92.28.109.120
381   user_241    BR887643  BR527456    25.21.170.224  196.154.185.135
8     user_292    BR140869  BR749468   169.238.247.43   150.145.134.81
554   user_293    BR589205  BR979682   238.85.179.101    2.164.196.246
724    user_31    BR618987  BR355022    58.169.109.65     150.22.84.24
708    user_72    BR245045  BR740180    86.102.145.75     217.80.40.11
1705    user_8    BR356787  BR662387  250.250.250.250  124.188.203.142

               LoginTime
850  2026-07-17 15:27:00
958  2026-08-27 11:18:00
1107 2026-07-04 02:35:00
730  2026-12-03 08:06:00
481  2026-08-11 00:00:00
26   2026-12-07 03:35:00
1026 2026-09-24 00:08:00
381  2026-09-25 14:05:00
8    2026-07-30 18:40:00
554  2026-08-23 03:56:00
724  2026-09-21 06:25:00
708  2026-07-09 12:56:00
1705 2026-08-05 07:06:00

In [15]:
print("===== Login Summary =====")

# Function to generate login summary
def login_summary(column):

    result = (
        authLogsDF
        .groupby(column)
        .agg(
            TotalLoginEvents=("UserName", "size"),
            UniqueUsers=("UserName", "nunique"),
            SuccessfulLogins=("EventType", lambda x: (x == "Success").sum()),
            FailedLogins=("EventType", lambda x: (x == "Failure").sum())
        )
        .reset_index()
        .sort_values(by="TotalLoginEvents", ascending=False)
    )

    return result


# List of columns
columns = [
    "City",
    "Country",
    "departmentName",
    "ServiceName",
    "month",
    "BrowserID",
    "MultiFactorType",
    "LoginAlert",
    "WithGeoFencing",
    "AuthType"
]

# Generate login summary for each column
for column in columns:
    print(f"\n{'='*15} {column} {'='*15}")
    print(login_summary(column))

===== Login Summary =====

=============== City ===============
        City  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
2      Delhi               295          207               165           110
3  Hyderabad               276          186               152            97
7       Pune               264          177               156            84
1    Chennai               256          180               160            75
4    Kolkata               256          181               148            83
6     Mumbai               247          168               156            69
5    Lucknow               229          162               135            71
0  Bengaluru               226          154               136            69

=============== Country ===============
  Country  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
0   India              2049          329              1208           658

=============== departmentName ===============
  departmentName  TotalLoginEvents  UniqueUsers  SuccessfulLogins  \
2             HR               408          252               236
0          Admin               335          202               218
5        Support               332          195               190
4          Sales               330          189               186
1        Finance               324          192               200
3             IT               320          189               178

   FailedLogins
2           137
0            83
5           115
4           115
1           100
3           108

=============== ServiceName ===============
  ServiceName  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
1         ERP               457          255               254           160
3        HRMS               408          227               242           136
0         CRM               405          222               242           118
4     Payroll               403          227               223           142
2     Finance               376          205               247           102

=============== month ===============
   month  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
11   Sep               236          174               137            80
8    May               203          145               124            59
4    Jan               185          142                97            68
7    Mar               185          135               112            56
6    Jun               180          132               111            54
10   Oct               177          133               113            50
1    Aug               174          132               107            54
5    Jul               168          131               100            53
0    Apr               160          124                93            48
9    Nov               159          118                88            60
3    Feb               142          113                81            49
2    Dec                80           72                45            27

=============== BrowserID ===============
     BrowserID  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
553   BR356787                50           42                24            26
179   BR175231                 2            2                 1             1
1461  BR768605                 2            2                 2             0
1760  BR893023                 2            2                 1             0
1411  BR743415                 2            2                 2             0
...        ...               ...          ...               ...           ...
662   BR406199                 1            1                 1             0
661   BR405936                 1            1                 0             1
660   BR405831                 1            1                 0             1
659   BR405504                 1            1                 1             0
1995  BR999285                 1            1                 1             0

[1996 rows x 5 columns]

=============== MultiFactorType ===============
     MultiFactorType  TotalLoginEvents  UniqueUsers  SuccessfulLogins  \
1              Email               543          268               317
2                SMS               518          243               311
0  Authenticator App               495          247               294

   FailedLogins
1           183
2           162
0           163

=============== LoginAlert ===============
  LoginAlert  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
0         No              1057          318               607           359
1        Yes               992          287               601           299

=============== WithGeoFencing ===============
  WithGeoFencing  TotalLoginEvents  UniqueUsers  SuccessfulLogins  \
0             No              1077          321               646
1            Yes               972          286               562

   FailedLogins
0           338
1           320

=============== AuthType ===============
    AuthType  TotalLoginEvents  UniqueUsers  SuccessfulLogins  FailedLogins
0  Biometric               595          283               346           196
1      OAuth               492          233               297           143
3        SSO               483          247               281           168
2   Password               479          249               284           151

In [8]:
print("===== User Login Profiling =====")

# User Login Profiling
userProfileDF = (
    authLogsDF
    .groupby("UserName")
    .agg(
        TotalLogins=("UserName", "size"),
        NoOfServices=("ServiceName", "nunique"),
        NoOfBrowsers=("BrowserID", "nunique"),
        NoOfCities=("City", "nunique"),
        NoOfIPs=("IPAddress", "nunique"),

        # Equivalent of collect_set()
        ServicesUsed=("ServiceName", lambda x: sorted(set(x.dropna()))),
        BrowsersUsed=("BrowserID", lambda x: sorted(set(x.dropna()))),
        AuthTypesUsed=("AuthType", lambda x: sorted(set(x.dropna()))),

        SuccessfulLogins=("EventType", lambda x: (x == "Success").sum()),
        FailedLogins=("EventType", lambda x: (x == "Failure").sum())
    )
    .reset_index()
)

# Calculate Success Rate
userProfileDF["SuccessRate"] = (
    (
        userProfileDF["SuccessfulLogins"]
        / userProfileDF["TotalLogins"]
    ) * 100
).round(2)

# Sort by Total Logins
userProfileDF = (
    userProfileDF
    .sort_values(by="TotalLogins", ascending=False)
    .reset_index(drop=True)
)

# Display the result
print(userProfileDF)

===== User Login Profiling =====
     UserName  TotalLogins  NoOfServices  NoOfBrowsers  NoOfCities  NoOfIPs  \
0     user_37           16             5            16           8       16
1    user_183           14             5            14           7       14
2    user_260           14             5            14           7       14
3    user_245           13             5            13           7       13
4     user_68           13             4            13           7       13
..        ...          ...           ...           ...         ...      ...
324  user_414            1             1             1           1        1
325  user_404            1             1             1           1        1
326  user_395            1             1             1           1        1
327  user_389            1             1             1           1        1
328    user_0            1             1             1           1        1

                           ServicesUsed  \
0    [CRM, ERP, Finance, HRMS, Payroll]
1    [CRM, ERP, Finance, HRMS, Payroll]
2    [CRM, ERP, Finance, HRMS, Payroll]
3    [CRM, ERP, Finance, HRMS, Payroll]
4             [CRM, ERP, HRMS, Payroll]
..                                  ...
324                               [ERP]
325                               [ERP]
326                               [ERP]
327                               [ERP]
328                               [ERP]

                                          BrowsersUsed  \
0    [BR116945, BR205814, BR215828, BR231413, BR417...
1    [BR127578, BR154856, BR165821, BR169608, BR420...
2    [BR315363, BR446600, BR459298, BR469755, BR564...
3    [BR133581, BR171046, BR231945, BR322256, BR454...
4    [BR124818, BR135410, BR180244, BR227324, BR248...
..                                                 ...
324                                         [BR356787]
325                                         [BR356787]
326                                         [BR356787]
327                                         [BR356787]
328                                         [BR356787]

                         AuthTypesUsed  SuccessfulLogins  FailedLogins  \
0    [Biometric, OAuth, Password, SSO]                11             3
1    [Biometric, OAuth, Password, SSO]                 9             5
2    [Biometric, OAuth, Password, SSO]                 8             3
3    [Biometric, OAuth, Password, SSO]                 8             4
4    [Biometric, OAuth, Password, SSO]                 9             1
..                                 ...               ...           ...
324                        [Biometric]                 0             1
325                        [Biometric]                 0             1
326                        [Biometric]                 1             0
327                        [Biometric]                 1             0
328                        [Biometric]                 0             1

     SuccessRate
0          68.75
1          64.29
2          57.14
3          61.54
4          69.23
..           ...
324         0.00
325         0.00
326       100.00
327       100.00
328         0.00

[329 rows x 12 columns]

In [18]:
print("===== Service Dependency Percentage =====")

# Total login records
totalLogins = len(authLogsDF)

# Service Dependency Analysis
serviceDependencyDF = (
    authLogsDF
    .groupby("ServiceName")
    .size()
    .reset_index(name="count")
)

# Calculate Usage Percentage
serviceDependencyDF["UsagePercentage"] = (
    (serviceDependencyDF["count"] * 100) / totalLogins
).round(2)

# Sort by Usage Percentage
serviceDependencyDF = (
    serviceDependencyDF
    .sort_values(by="UsagePercentage", ascending=False)
    .reset_index(drop=True)
)

# Display result
print(serviceDependencyDF)

===== Service Dependency Percentage =====
  ServiceName  count  UsagePercentage
0         ERP    457            22.30
1        HRMS    408            19.91
2         CRM    405            19.77
3     Payroll    403            19.67
4     Finance    376            18.35

In [20]:
print("===== User Contribution Percentage on Service =====")

# Successful login events only
userServiceContributionDF = (
    authLogsDF[authLogsDF["EventType"] == "Success"]
    .groupby(["ServiceName", "UserName"])
    .size()
    .reset_index(name="UserLogins")
)

# Total logins for each service
totalServiceLoginsDF = (
    authLogsDF
    .groupby("ServiceName")
    .size()
    .reset_index(name="TotalServiceLogins")
)

# Merge both DataFrames
finalDF = (
    userServiceContributionDF
    .merge(totalServiceLoginsDF, on="ServiceName", how="inner")
)

# Calculate contribution percentage
finalDF["ContributionPercent"] = (
    (
        finalDF["UserLogins"]
        / finalDF["TotalServiceLogins"]
    ) * 100
).round(2)

# Sort by contribution percentage
finalDF = (
    finalDF
    .sort_values(by="ContributionPercent", ascending=False)
    .reset_index(drop=True)
)

# Display result
print(finalDF)

===== User Contribution Percentage on Service =====
    ServiceName  UserName  UserLogins  TotalServiceLogins  ContributionPercent
0       Finance    user_7           4                 376                 1.06
1       Finance   user_35           4                 376                 1.06
2       Finance  user_142           4                 376                 1.06
3       Finance  user_293           4                 376                 1.06
4       Finance  user_241           4                 376                 1.06
..          ...       ...         ...                 ...                  ...
816         ERP  user_202           1                 457                 0.22
817         ERP  user_199           1                 457                 0.22
818         ERP  user_197           1                 457                 0.22
819         ERP  user_281           1                 457                 0.22
820         ERP  user_196           1                 457                 0.22

[821 rows x 5 columns]

In [5]:
import pandas as pd

print("===== Was This You =====")

# Current User
current_User = "user_170"

# Filter only successful login events of the current user
wasThisYouDF = authLogsDF[
    (authLogsDF["UserName"] == current_User) &
    (authLogsDF["EventName"] == "Login") &
    (authLogsDF["EventType"] == "Success")
].copy()

# Convert TimeStamp to datetime
wasThisYouDF["LoginTime"] = pd.to_datetime(
    wasThisYouDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

# Sort by login time
wasThisYouDF = wasThisYouDF.sort_values("LoginTime")

# Previous City and Previous IP
wasThisYouDF["PreviousCity"] = wasThisYouDF["City"].shift(1)
wasThisYouDF["PreviousIP"] = wasThisYouDF["IPAddress"].shift(1)

# Detect change in City or IP
wasThisYouDF = wasThisYouDF[
    (wasThisYouDF["City"] != wasThisYouDF["PreviousCity"]) |
    (wasThisYouDF["IPAddress"] != wasThisYouDF["PreviousIP"])
]

# Select required columns
wasThisYouDF = wasThisYouDF[
    [
        "TimeStamp",
        "City",
        "IPAddress",
        "PreviousCity",
        "PreviousIP"
    ]
]

# Display result
print(wasThisYouDF)

===== Was This You =====
Empty DataFrame
Columns: [TimeStamp, City, IPAddress, PreviousCity, PreviousIP]
Index: []

In [9]:
print("===== Suspicious Login Risk Analysis =====")

import pandas as pd

# ----------------------------------------------------
# Create Copy
# ----------------------------------------------------

riskDF = authLogsDF.copy()

# ----------------------------------------------------
# Convert Timestamp
# ----------------------------------------------------

riskDF["LoginTime"] = pd.to_datetime(
    riskDF["TimeStamp"],
    format="%d-%m-%Y %H:%M"
)

# ----------------------------------------------------
# Sort User Login--------------------------------

riskDF = riskDF.sort_values(
    ["UserName", "LoginTime"]
)

# ----------------------------------------------------
# Previous Login Information
# ----------------------------------------------------

riskDF["PrevEventType"] = (
    riskDF.groupby("UserName")["EventType"].shift(1)
)

riskDF["PrevBrowser"] = (
    riskDF.groupby("UserName")["BrowserID"].shift(1)
)

riskDF["PrevIP"] = (
    riskDF.groupby("UserName")["IPAddress"].shift(1)
)

riskDF["PrevCity"] = (
    riskDF.groupby("UserName")["City"].shift(1)s
# --------------------
)

riskDF["PrevLoginTime"] = (
    riskDF.groupby("UserName")["LoginTime"].shift(1)
)

# ----------------------------------------------------
# Time Difference
# ----------------------------------------------------

riskDF["TimeDifferenceMinutes"] = (
    riskDF["LoginTime"] -
    riskDF["PrevLoginTime"]
).dt.total_seconds() / 60

# ----------------------------------------------------
# Initialize Risk Score
# ----------------------------------------------------

riskDF["RiskScore"] = 0

# ----------------------------------------------------
# Rule 1
# Previous Login Failed
# ----------------------------------------------------

riskDF.loc[
    riskDF["PrevEventType"] == "Failure",
    "RiskScore"
] += 20

# ----------------------------------------------------
# Rule 2
# Success within 5 Minutes
# ----------------------------------------------------

riskDF.loc[
    (
        (riskDF["EventType"] == "Success") &
        (riskDF["TimeDifferenceMinutes"] <= 5)
    ),
    "RiskScore"
] += 20

# ----------------------------------------------------
# Rule 3
# Browser Changed
# ----------------------------------------------------

riskDF.loc[
    riskDF["BrowserID"] != riskDF["PrevBrowser"],
    "RiskScore"
] += 15

# ----------------------------------------------------
# Rule 4
# IP Changed
# ----------------------------------------------------

riskDF.loc[
    riskDF["IPAddress"] != riskDF["PrevIP"],
    "RiskScore"
] += 15

# ----------------------------------------------------
# Rule 5
# City Changed
# ----------------------------------------------------

riskDF.loc[
    riskDF["City"] != riskDF["PrevCity"],
    "RiskScore"
] += 20

# ----------------------------------------------------
# Rule 6
# Login Alert
# ----------------------------------------------------

riskDF.loc[
    riskDF["LoginAlert"] == "Yes",
    "RiskScore"
] += 20

# ----------------------------------------------------
# Rule 7
# Remember Device = No
# ----------------------------------------------------

riskDF.loc[
    riskDF["RememberDevice"] == "No",
    "RiskScore"
] += 10

# ----------------------------------------------------
# Risk Level
# ----------------------------------------------------

riskDF["RiskLevel"] = "Low"

riskDF.loc[
    riskDF["RiskScore"] >= 31,
    "RiskLevel"
] = "Medium"

riskDF.loc[
    riskDF["RiskScore"] >= 61,
    "RiskLevel"
] = "High"

# ----------------------------------------------------
# Show Only Suspicious Logins
# ----------------------------------------------------

suspiciousLogins = riskDF[
    riskDF["RiskScore"] >= 31
]

print(suspiciousLogins[
    [
        "UserName",
        "LoginTime",
        "City",
        "IPAddress",
        "BrowserID",
        "RiskScore",
        "RiskLevel"
    ]
].sort_values("RiskScore", ascending=False))

===== Suspicious Login Risk Analysis =====
      UserName           LoginTime       City        IPAddress BrowserID  \
1567   user_74 2026-07-02 22:32:00     Mumbai    14.144.240.49  BR149634
662   user_126 2026-10-05 19:19:00    Kolkata    42.77.215.119  BR664913
1239  user_229 2026-05-19 20:04:00      Delhi  228.170.179.103  BR536304
344    user_40 2026-02-16 08:12:00  Hyderabad    43.51.113.223  BR269966
1134  user_253 2026-12-07 19:22:00      Delhi    8.232.220.232  BR242409
...        ...                 ...        ...              ...       ...
1010   user_70 2026-07-17 22:43:00      Delhi     48.76.48.191  BR413500
114    user_61 2026-09-29 07:59:00    Lucknow    143.141.1.212  BR207629
750   user_240 2026-11-30 12:33:00    Lucknow   113.188.74.215  BR398701
1804   user_87 2026-07-20 14:19:00  Bengaluru   159.103.82.177  BR757094
1046  user_291 2026-11-10 19:12:00    Lucknow     72.49.165.80  BR319807

      RiskScore RiskLevel
1567        100      High
662         100      High
1239        100      High
344         100      High
1134        100      High
...         ...       ...
1010         40    Medium
114          40    Medium
750          40    Medium
1804         40    Medium
1046         40    Medium

[2021 rows x 7 columns]

In [9]:
print("===== Advanced Suspicious Login Risk Analysis =====")

riskDF = authLogsDF.copy()


# Convert Timestamp
riskDF["LoginTime"] = pd.to_datetime(
    riskDF["TimeStamp"],
    format="%d-%m-%Y %H:%M"
)


# Sort Data
riskDF = riskDF.sort_values(
    ["UserName", "LoginTime"]
)


# Previous Login Details
riskDF["PrevEventType"] = riskDF.groupby("UserName")["EventType"].shift(1)
riskDF["PrevBrowser"] = riskDF.groupby("UserName")["BrowserID"].shift(1)
riskDF["PrevIP"] = riskDF.groupby("UserName")["IPAddress"].shift(1)
riskDF["PrevCity"] = riskDF.groupby("UserName")["City"].shift(1)
riskDF["PrevSession"] = riskDF.groupby("UserName")["SessionID"].shift(1)
riskDF["PrevLoginTime"] = riskDF.groupby("UserName")["LoginTime"].shift(1)


# Time Difference
riskDF["TimeDifferenceMinutes"] = (
    riskDF["LoginTime"] -
    riskDF["PrevLoginTime"]
).dt.total_seconds() / 60


# Risk Score
riskDF["RiskScore"] = 0
riskDF["Reason"] = ""


# Failure -> Success + New Session + New Browser + New IP
highRisk = (
    (riskDF["PrevEventType"] == "Failure") &
    (riskDF["EventType"] == "Success") &
    (riskDF["TimeDifferenceMinutes"] <= 5) &
    (riskDF["BrowserID"] != riskDF["PrevBrowser"]) &
    (riskDF["IPAddress"] != riskDF["PrevIP"]) &
    (riskDF["SessionID"] != riskDF["PrevSession"])
    
)

riskDF.loc[highRisk, "RiskScore"] += 60
riskDF.loc[highRisk, "Reason"] += "Failure→Success + Browser/IP/Session Changed; "



# Impossible Travel
impossibleTravel = (
    (riskDF["City"] != riskDF["PrevCity"]) &
    (riskDF["TimeDifferenceMinutes"] <= 30)
)

riskDF.loc[impossibleTravel, "RiskScore"] += 30
riskDF.loc[impossibleTravel, "Reason"] += "Impossible Travel; "



# Login Alert
loginAlert = riskDF["LoginAlert"] == "Yes"

riskDF.loc[loginAlert, "RiskScore"] += 20
riskDF.loc[loginAlert, "Reason"] += "Login Alert; "



# Geo Fencing Disabled
geoRisk = riskDF["WithGeoFencing"] == "No"

riskDF.loc[geoRisk, "RiskScore"] += 25
riskDF.loc[geoRisk, "Reason"] += "Geo Fencing Disabled; "


# Remember Device = No
rememberRisk = riskDF["RememberDevice"] == "No"

riskDF.loc[rememberRisk, "RiskScore"] += 10
riskDF.loc[rememberRisk, "Reason"] += "Unknown Device; "


# Risk Level
riskDF["RiskLevel"] = np.select(
    [
        riskDF["RiskScore"] >= 61,
        riskDF["RiskScore"] >= 31
    ],
    [
        "High",
        "Medium"
    ],
    default="Low"
)


# Show Suspicious Logins
suspiciousLogins = riskDF[
    riskDF["RiskScore"] >= 31
]

print(
    suspiciousLogins[
        [
            "UserName",
            "LoginTime",
            "City",
            "IPAddress",
            "BrowserID",
            "SessionID",
            "RiskScore",
            "RiskLevel",
            "Reason"
        ]
    ]
    .sort_values("RiskScore", ascending=False)
)

===== Advanced Suspicious Login Risk Analysis =====
      UserName           LoginTime       City        IPAddress BrowserID  \
1993   user_98 2026-07-27 13:28:00    Lucknow     217.4.85.231  BR898209
2001  user_999 2026-07-10 10:08:00     Mumbai         20.1.1.1  BR356787
2017  user_858 2026-09-27 23:46:00       Pune         30.1.1.2  BR356787
2018  user_858 2026-09-27 23:46:00    Chennai         30.1.1.3  BR356787
49    user_231 2026-05-16 10:42:00    Kolkata    136.94.102.81  BR900152
...        ...                 ...        ...              ...       ...
1943  user_131 2026-05-05 01:02:00      Delhi    209.94.21.150  BR558348
1382  user_263 2026-05-03 18:23:00    Chennai     66.11.216.12  BR662072
704   user_260 2026-12-13 06:41:00  Hyderabad   134.243.103.83  BR446600
1182  user_259 2026-11-18 14:45:00  Hyderabad  225.127.174.119  BR406246
2019    user_0 2026-07-12 10:00:00      Delhi  250.250.250.250  BR356787

      SessionID  RiskScore RiskLevel  \
1993  SID186382         85      High
2001  SID832052         65      High
2017  SID832052         65      High
2018  SID832052         65      High
49    SID994253         55    Medium
...         ...        ...       ...
1943  SID291445         35    Medium
1382  SID697525         35    Medium
704   SID405314         35    Medium
1182  SID291055         35    Medium
2019  SID832052         35    Medium

                                                 Reason
1993  Impossible Travel; Login Alert; Geo Fencing Di...
2001  Impossible Travel; Geo Fencing Disabled; Unkno...
2017  Impossible Travel; Geo Fencing Disabled; Unkno...
2018  Impossible Travel; Geo Fencing Disabled; Unkno...
49    Login Alert; Geo Fencing Disabled; Unknown Dev...
...                                                 ...
1943             Geo Fencing Disabled; Unknown Device;
1382             Geo Fencing Disabled; Unknown Device;
704              Geo Fencing Disabled; Unknown Device;
1182             Geo Fencing Disabled; Unknown Device;
2019             Geo Fencing Disabled; Unknown Device;

[826 rows x 9 columns]

In [7]:
print("===== Advanced Suspicious Login Risk Analysis =====")

# Create Copy
riskDF = authLogsDF.copy()


# Convert Timestamp
riskDF["LoginTime"] = pd.to_datetime(
    riskDF["TimeStamp"],
    format="%d-%m-%Y %H:%M"
)


# Sort User Logins
riskDF = riskDF.sort_values(
    ["UserName", "LoginTime"]
)


# Previous Login Information
riskDF["PrevEventType"] = riskDF.groupby("UserName")["EventType"].shift(1)
riskDF["PrevEventName"] = riskDF.groupby("UserName")["EventName"].shift(1)
riskDF["PrevBrowser"] = riskDF.groupby("UserName")["BrowserID"].shift(1)
riskDF["PrevIP"] = riskDF.groupby("UserName")["IPAddress"].shift(1)
riskDF["PrevState"] = riskDF.groupby("UserName")["State"].shift(1)
riskDF["PrevLoginTime"] = riskDF.groupby("UserName")["LoginTime"].shift(1)


# Time Difference (Minutes)
riskDF["TimeDifferenceMinutes"] = (
    riskDF["LoginTime"] -
    riskDF["PrevLoginTime"]
).dt.total_seconds() / 60


# Initialize Risk Score
riskDF["RiskScore"] = 0
riskDF["Reason"] = ""



# Failed Login → Successful Login
# within 5 min + Browser Changed + IP Changed
highRisk = (
    (riskDF["PrevEventName"] == "Login") &
    (riskDF["EventName"] == "Login") &
    (riskDF["PrevEventType"] == "Failure") &
    (riskDF["EventType"] == "Success") &
    (riskDF["TimeDifferenceMinutes"] <= 5) &
    (riskDF["BrowserID"] != riskDF["PrevBrowser"]) &
    (riskDF["IPAddress"] != riskDF["PrevIP"])
)

riskDF.loc[highRisk, "RiskScore"] += 60
riskDF.loc[highRisk, "Reason"] += (
    "Failure→Success within 5 min with Browser & IP Changed; "
)





# Impossible Travel
# State changed within 30 minutes


impossibleTravel = (
    (riskDF["PrevEventName"] == "Login") &
    (riskDF["EventName"] == "Login") &
    (riskDF["PrevState"].notna()) &
    (riskDF["State"] != riskDF["PrevState"]) &
    (riskDF["TimeDifferenceMinutes"] <= 30)
)

riskDF.loc[impossibleTravel, "RiskScore"] += 30
riskDF.loc[impossibleTravel, "Reason"] += (
    "Impossible Travel (State Changed within 30 min); "
)

 
# Login Alert
loginAlert = (
    riskDF["LoginAlert"] == "Yes"
)

riskDF.loc[loginAlert, "RiskScore"] += 20
riskDF.loc[loginAlert, "Reason"] += "Login Alert; "



# Geo Fencing Disabled
geoRisk = (
    riskDF["WithGeoFencing"] == "No"
)

riskDF.loc[geoRisk, "RiskScore"] += 25
riskDF.loc[geoRisk, "Reason"] += "Geo Fencing Disabled; "


# Remember Device = No
unknownDevice = (
    riskDF["RememberDevice"] == "No"
)

riskDF.loc[unknownDevice, "RiskScore"] += 10
riskDF.loc[unknownDevice, "Reason"] += "Unknown Device; "


# Assign Risk Level
riskDF["RiskLevel"] = np.select(
    [
        riskDF["RiskScore"] >= 61,
        riskDF["RiskScore"] >= 31
    ],
    [
        "High",
        "Medium"
    ],
    default="Low"
)


# Show Only Medium & High Risk Logins
suspiciousLogins = riskDF[
    riskDF["RiskScore"] >= 31
]

print(
    suspiciousLogins[
        [
            "UserName",
            "LoginTime",
            "State",
            "IPAddress",
            "BrowserID",
            "RiskScore",
            "RiskLevel",
            "Reason"
        ]
    ]
    .sort_values("RiskScore", ascending=False)
)

===== Advanced Suspicious Login Risk Analysis =====
      UserName           LoginTime        State        IPAddress BrowserID  \
1958   user_37 2026-09-13 05:34:00        Delhi    100.5.105.174  BR480303
67    user_165 2026-05-19 14:16:00   Tamil Nadu   93.132.226.128  BR659572
1057  user_254 2026-01-17 14:12:00  West Bengal  176.226.229.162  BR850855
1678  user_174 2026-04-19 14:13:00    Telangana  113.146.171.251  BR671540
581    user_55 2026-10-11 13:07:00   Tamil Nadu   101.222.92.136  BR313951
...        ...                 ...          ...              ...       ...
1270  user_241 2026-02-16 01:16:00    Karnataka   41.218.117.109  BR786663
1743  user_240 2026-02-11 16:09:00   Tamil Nadu    102.21.26.239  BR582329
883    user_24 2026-06-28 00:09:00  West Bengal      10.21.7.137  BR353163
1639  user_239 2026-02-14 02:21:00   Tamil Nadu     90.14.40.177  BR120863
2001  user_999 2026-07-10 10:08:00   Tamil Nadu         20.1.1.1  BR356787

      RiskScore RiskLevel                                             Reason
1958         55    Medium  Login Alert; Geo Fencing Disabled; Unknown Dev...
67           55    Medium  Login Alert; Geo Fencing Disabled; Unknown Dev...
1057         55    Medium  Login Alert; Geo Fencing Disabled; Unknown Dev...
1678         55    Medium  Login Alert; Geo Fencing Disabled; Unknown Dev...
581          55    Medium  Login Alert; Geo Fencing Disabled; Unknown Dev...
...         ...       ...                                                ...
1270         35    Medium             Geo Fencing Disabled; Unknown Device;
1743         35    Medium             Geo Fencing Disabled; Unknown Device;
883          35    Medium             Geo Fencing Disabled; Unknown Device;
1639         35    Medium             Geo Fencing Disabled; Unknown Device;
2001         35    Medium             Geo Fencing Disabled; Unknown Device;

[825 rows x 8 columns]

In [7]:
print("===== User Contribution & Week-over-Week Trend =====")

# Only successful logins
successDF = authLogsDF[authLogsDF["EventType"] == "Success"].copy()

# Convert timestamp
successDF["LoginTime"] = pd.to_datetime(
    successDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

# Week Number
successDF["Week"] = successDF["LoginTime"].dt.isocalendar().week

# User logins per Service per Week
userWeekDF = (
    successDF
    .groupby(["ServiceName", "Week", "UserName"])
    .size()
    .reset_index(name="UserLogins")
)

# Total Service logins per Week
serviceWeekDF = (
    successDF
    .groupby(["ServiceName", "Week"])
    .size()
    .reset_index(name="TotalLogins")
    )

# Merge
finalDF = userWeekDF.merge(
    serviceWeekDF,
    on=["ServiceName", "Week"]
)

# Contribution %
finalDF["ContributionPercent"] = (
    finalDF["UserLogins"]
    / finalDF["TotalLogins"]
    * 100
).round(2)

# Week-over-Week Change
finalDF = finalDF.sort_values(
    ["ServiceName", "UserName", "Week"]
)

finalDF["WoWChange"] = (
    finalDF
    .groupby(["ServiceName", "UserName"])["ContributionPercent"]
    .diff()
    .round(2)
)

print(finalDF)

===== User Contribution & Week-over-Week Trend =====
     ServiceName  Week  UserName  UserLogins  TotalLogins  \
223          CRM    47    user_1           1            5
230          CRM    49    user_1           1            8
151          CRM    33   user_10           1            6
94           CRM    22  user_103           1            6
23           CRM     6  user_106           1            4
...          ...   ...       ...         ...          ...
1014     Payroll    12   user_94           1            5
1153     Payroll    41   user_94           1            7
1040     Payroll    19   user_97           1            5
974      Payroll     3   user_98           1            4
1085     Payroll    28   user_98           1            4

      ContributionPercent  WoWChange
223                 20.00        NaN
230                 12.50      -7.50
151                 16.67        NaN
94                  16.67        NaN
23                  25.00        NaN
...                   ...        ...
1014                20.00        NaN
1153                14.29      -5.71
1040                20.00        NaN
974                 25.00        NaN
1085                25.00       0.00

[1189 rows x 7 columns]

In [8]:
print("===== User Login Activity Trend =====")

# Keep Only Successful Logins
successDF = authLogsDF[
    authLogsDF["EventType"] == "Success"
].copy()


# Convert Timestamp
successDF["LoginTime"] = pd.to_datetime(
    successDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)


# Extract Week Number
successDF["Week"] = successDF["LoginTime"].dt.isocalendar().week


# User Logins Per Week
userWeekDF = (
    successDF
    .groupby(["UserName", "Week"])
    .size()
    .reset_index(name="UserLogins")
)


# Sort Data
userWeekDF = userWeekDF.sort_values(
    ["UserName", "Week"]
)


# Week-over-Week Login Change
userWeekDF["WoWLoginChange"] = (
    userWeekDF
    .groupby("UserName")["UserLogins"]
    .diff()
)


# Trend
userWeekDF["Trend"] = userWeekDF["WoWLoginChange"].apply(
    lambda x: "First Week" if pd.isna(x)
    else "Increase" if x > 0
    else "Decrease" if x < 0
    else "No Change"
)


# Print Result
print(userWeekDF)

===== User Login Activity Trend =====
      UserName  Week  UserLogins  WoWLoginChange       Trend
0       user_1     5           1             NaN  First Week
1       user_1    23           1             0.0   No Change
2       user_1    29           1             0.0   No Change
3       user_1    34           1             0.0   No Change
4       user_1    36           1             0.0   No Change
...        ...   ...         ...             ...         ...
1142   user_99     7           1             0.0   No Change
1143   user_99    15           1             0.0   No Change
1144   user_99    16           1             0.0   No Change
1145   user_99    43           1             0.0   No Change
1146  user_999    28           2             NaN  First Week

[1147 rows x 5 columns]

In [ ]:
print("===== Login Time Summary =====")

# Current user
currentUser = "user_170"

# Filter successful login events for the user
loginSummaryDF = authLogsDF[
    (authLogsDF["UserName"] == currentUser) &
    (authLogsDF["EventName"] == "Login") &
    (authLogsDF["EventType"] == "Success")
].copy()

# Convert timestamp
loginSummaryDF["LoginTime"] = pd.to_datetime(
    loginSummaryDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

# Extract date and hour
loginSummaryDF["LoginDate"] = loginSummaryDF["LoginTime"].dt.date
loginSummaryDF["LoginHour"] = loginSummaryDF["LoginTime"].dt.hour

# Group by date and hour
loginSummaryDF = (
    loginSummaryDF
    .groupby(["LoginDate", "LoginHour"])
    .size()
    .reset_index(name="LoginCount")
    .sort_values(by=["LoginDate", "LoginHour"])
    .reset_index(drop=True)
    )

# Display result
print(loginSummaryDF)

# new use case

In [30]:
print("===== Core Feature Engineering =====")

# --------------------------------------------------
# 1. Prepare Login Data
# --------------------------------------------------

loginDF = authLogsDF[
    authLogsDF["EventName"] == "Login"
].copy()

loginDF["LoginTime"] = pd.to_datetime(
    loginDF["TimeStamp"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

loginDF = (
    loginDF
    .sort_values(["UserName", "LoginTime"])
    .reset_index(drop=True)
)


# --------------------------------------------------
# 2. Previous Login Information
# --------------------------------------------------

loginDF["PreviousLoginTime"] = (
    loginDF
    .groupby("UserName")["LoginTime"]
    .shift(1)
)

loginDF["PreviousIP"] = (
    loginDF
    .groupby("UserName")["IPAddress"]
    .shift(1)
)

loginDF["PreviousBrowser"] = (
    loginDF
    .groupby("UserName")["BrowserID"]
    .shift(1)
)

loginDF["PreviousState"] = (
    loginDF
    .groupby("UserName")["State"]
    .shift(1)
)

loginDF["PreviousLatitude"] = (
    loginDF
    .groupby("UserName")["Latitude"]
    .shift(1)
)

loginDF["PreviousLongitude"] = (
    loginDF
    .groupby("UserName")["Longitude"]
    .shift(1)
)


# --------------------------------------------------
# 3. Time Difference
# --------------------------------------------------

loginDF["TimeDifferenceMinutes"] = (
    loginDF["LoginTime"]
    -
    loginDF["PreviousLoginTime"]
).dt.total_seconds() / 60


# --------------------------------------------------
# 4. IP Change
# --------------------------------------------------

loginDF["IPChanged"] = (
    loginDF["IPAddress"]
    != loginDF["PreviousIP"]
).astype(int)


# --------------------------------------------------
# 5. Browser Change
# --------------------------------------------------

loginDF["BrowserChanged"] = (
    loginDF["BrowserID"]
    != loginDF["PreviousBrowser"]
).astype(int)


# --------------------------------------------------
# 6. State Change
# --------------------------------------------------

loginDF["StateChanged"] = (
    loginDF["State"]
    != loginDF["PreviousState"]
).astype(int)


# --------------------------------------------------
# 7. Login Failure
# --------------------------------------------------

loginDF["LoginFailure"] = (
    loginDF["EventType"] == "Failure"
).astype(int)


# First login has no previous login
firstLogin = (
    loginDF["PreviousLoginTime"].isna()
)

loginDF.loc[
    firstLogin,
    [
        "IPChanged",
        "BrowserChanged",
        "StateChanged"
    ]
] = 0


# --------------------------------------------------
# 8. Distance Between Logins
# --------------------------------------------------

R = 6371

lat1 = np.radians(
    loginDF["PreviousLatitude"]
)

lon1 = np.radians(
    loginDF["PreviousLongitude"]
)

lat2 = np.radians(
    loginDF["Latitude"]
)

lon2 = np.radians(
    loginDF["Longitude"]
)

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    np.sin(dlat / 2) ** 2
    +
    np.cos(lat1)
    * np.cos(lat2)
    * np.sin(dlon / 2) ** 2
)

c = 2 * np.arctan2(
    np.sqrt(a),
    np.sqrt(1 - a)
)

loginDF["DistanceKM"] = R * c

loginDF.loc[
    firstLogin,
    "DistanceKM"
] = 0


# --------------------------------------------------
# 9. Travel Speed
# --------------------------------------------------

loginDF["TimeDifferenceHours"] = (
    loginDF["TimeDifferenceMinutes"] / 60
)

loginDF["TravelSpeedKMH"] = np.where(
    loginDF["TimeDifferenceHours"] > 0,
    loginDF["DistanceKM"]
    /
    loginDF["TimeDifferenceHours"],
    0
)

loginDF.loc[
    firstLogin,
    "TravelSpeedKMH"
] = 0


# --------------------------------------------------
# 10. Final ML Features
# --------------------------------------------------

coreFeatureColumns = [
    "IPChanged",
    "BrowserChanged",
    "StateChanged",
    "LoginFailure",
    "TimeDifferenceMinutes",
    "DistanceKM",
    "TravelSpeedKMH"
]


# --------------------------------------------------
# 11. Create ML Dataset
# --------------------------------------------------

coreMLDF = loginDF[
    ["UserName", "LoginTime"] +
    coreFeatureColumns
].copy()


# --------------------------------------------------
# 12. Handle Invalid Values
# --------------------------------------------------

coreMLDF[coreFeatureColumns] = (
    coreMLDF[coreFeatureColumns]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)


print("\n===== Core Feature Engineering Completed =====")

print(
    "Login Observations:",
    len(coreMLDF)
)

print(
    "Number of ML Features:",
    len(coreFeatureColumns)
)

print("\nFeature Columns:")
print(coreFeatureColumns)

print("\nFirst 5 Rows:")
display(coreMLDF.head())

===== Core Feature Engineering =====

===== Core Feature Engineering Completed =====
Login Observations: 1379
Number of ML Features: 7

Feature Columns:
['IPChanged', 'BrowserChanged', 'StateChanged', 'LoginFailure', 'TimeDifferenceMinutes', 'DistanceKM', 'TravelSpeedKMH']

First 5 Rows:

,UserName,LoginTime,IPChanged,BrowserChanged,StateChanged,LoginFailure,TimeDifferenceMinutes,DistanceKM,TravelSpeedKMH
0,user_0,2026-07-12 10:00:00,0,0,0,1,0.0,0.000000,0.000000
1,user_1,2026-07-12 10:01:00,0,0,0,1,0.0,0.000000,0.000000
2,user_1,2026-07-17 15:27:00,1,1,1,0,7526.0,289.779181,2.310225
3,user_1,2026-08-08 10:50:00,1,1,1,1,31403.0,501.600241,0.958380
4,user_1,2026-09-04 05:28:00,0,0,0,0,38558.0,0.606627,0.000944

In [45]:
print("===== Travel Feasibility Analysis =====")

def classifyTravelSpeed(speed):

    if speed <= 30:
        return "Local Travel"

    elif speed <= 120:
        return "Road Travel Possible"

    elif speed <= 250:
        return "High Speed Travel"

    elif speed <= 900:
        return "Air Travel Possible"

    else:
        return "Impossible Travel"


coreMLDF["TravelCategory"] = (
    coreMLDF["TravelSpeedKMH"]
    .apply(classifyTravelSpeed)
)


print("\n===== Travel Category Distribution =====")

print(
    coreMLDF["TravelCategory"]
    .value_counts()
)


print("\n===== Highest Travel Speeds =====")

print(
    coreMLDF[
        [
            "UserName",
            "LoginTime",
            "TimeDifferenceMinutes",
            "DistanceKM",
            "TravelSpeedKMH",
            "TravelCategory"
        ]
    ]
    .sort_values(
        "TravelSpeedKMH",
        ascending=False
    )
    .head(20)
)

===== Travel Feasibility Analysis =====

===== Travel Category Distribution =====
TravelCategory
Local Travel            1341
Road Travel Possible      28
Impossible Travel          6
High Speed Travel          3
Air Travel Possible        1
Name: count, dtype: int64

===== Highest Travel Speeds =====
      UserName           LoginTime  TimeDifferenceMinutes   DistanceKM  \
1340  user_954 2026-07-11 09:01:00                    1.0  1586.834215
1343  user_954 2026-07-11 09:04:00                    1.0   419.275388
1341  user_954 2026-07-11 09:02:00                    1.0   417.963199
1378  user_999 2026-07-10 10:08:00                    8.0  1258.378515
279   user_155 2027-02-21 11:18:00                   28.0  1753.701325
1008   user_37 2026-02-16 07:25:00                   44.0   730.770680
898   user_285 2027-03-19 11:28:00                  163.0  1653.809504
1122   user_55 2027-01-26 03:32:00                  342.0  1150.691162
1154   user_60 2027-01-19 04:30:00                  217.0   618.542212
1271   user_83 2027-03-14 02:00:00                  593.0  1303.078724
1342  user_954 2026-07-11 09:03:00                    1.0     1.950652
456   user_195 2027-01-04 09:55:00                  921.0  1736.773191
1344  user_954 2026-07-11 09:05:00                    1.0     1.697356
382   user_179 2027-04-12 12:18:00                 1105.0  1560.171716
1225   user_75 2027-03-24 03:53:00                  538.0   737.962274
948   user_294 2027-01-01 11:37:00                  536.0   733.596982
1362   user_98 2027-03-07 06:42:00                  383.0   501.597440
940   user_292 2027-02-28 03:30:00                 1649.0  1756.651277
396   user_181 2027-01-10 13:46:00                 1282.0  1360.998678
1364   user_98 2027-04-07 23:45:00                 1719.0  1741.240399

      TravelSpeedKMH        TravelCategory
1340    95210.052879     Impossible Travel
1343    25156.523285     Impossible Travel
1341    25077.791920     Impossible Travel
1378     9437.838859     Impossible Travel
279      3757.931410     Impossible Travel
1008      996.505473     Impossible Travel
898       608.764235   Air Travel Possible
1122      201.875642     High Speed Travel
1154      171.025496     High Speed Travel
1271      131.846077     High Speed Travel
1342      117.039103  Road Travel Possible
456       113.144833  Road Travel Possible
1344      101.841344  Road Travel Possible
382        84.715206  Road Travel Possible
1225       82.300625  Road Travel Possible
948        82.119065  Road Travel Possible
1362       78.579233  Road Travel Possible
940        63.916966  Road Travel Possible
396        63.697286  Road Travel Possible
1364       60.776279  Road Travel Possible

In [46]:
print("===== Impossible Travel Feature =====")

coreMLDF["ImpossibleTravel"] = (
    coreMLDF["TravelSpeedKMH"] > 900
).astype(int)

print("\n===== Impossible Travel Distribution =====")

print(
    coreMLDF["ImpossibleTravel"]
    .value_counts()
)

print("\n===== Impossible Travel Cases =====")

print(
    coreMLDF[
        coreMLDF["ImpossibleTravel"] == 1
    ][
        [
            "UserName",
            "LoginTime",
            "TimeDifferenceMinutes",
            "DistanceKM",
            "TravelSpeedKMH",
            "TravelCategory",
            "ImpossibleTravel"
        ]
    ]
    .sort_values(
        "TravelSpeedKMH",
        ascending=False
    )
)

===== Impossible Travel Feature =====

===== Impossible Travel Distribution =====
ImpossibleTravel
0    1373
1       6
Name: count, dtype: int64

===== Impossible Travel Cases =====
      UserName           LoginTime  TimeDifferenceMinutes   DistanceKM  \
1340  user_954 2026-07-11 09:01:00                    1.0  1586.834215
1343  user_954 2026-07-11 09:04:00                    1.0   419.275388
1341  user_954 2026-07-11 09:02:00                    1.0   417.963199
1378  user_999 2026-07-10 10:08:00                    8.0  1258.378515
279   user_155 2027-02-21 11:18:00                   28.0  1753.701325
1008   user_37 2026-02-16 07:25:00                   44.0   730.770680

      TravelSpeedKMH     TravelCategory  ImpossibleTravel
1340    95210.052879  Impossible Travel                 1
1343    25156.523285  Impossible Travel                 1
1341    25077.791920  Impossible Travel                 1
1378     9437.838859  Impossible Travel                 1
279      3757.931410  Impossible Travel                 1
1008      996.505473  Impossible Travel                 1

In [47]:
print("===== Feature Quality Check =====")

# Only the 7 ML features
X_core = coreMLDF[coreFeatureColumns].copy()

print("Shape:", X_core.shape)


# --------------------------------------------------
# Missing Values
# --------------------------------------------------

print("\n===== Missing Values =====")

print(
    X_core.isnull().sum().sum()
)


# --------------------------------------------------
# Infinite Values
# --------------------------------------------------

print("\n===== Infinite Values =====")

print(
    np.isinf(X_core).sum().sum()
)


# --------------------------------------------------
# Data Types
# --------------------------------------------------

print("\n===== Data Types =====")

print(
    X_core.dtypes
)


# --------------------------------------------------
# Constant Features
# --------------------------------------------------

print("\n===== Constant Features =====")

constantFeatures = [
    col
    for col in X_core.columns
    if X_core[col].nunique() <= 1
]

print(constantFeatures)


# --------------------------------------------------
# Feature Statistics
# --------------------------------------------------

print("\n===== Feature Statistics =====")

display(
    X_core.describe().T
)

===== Feature Quality Check =====
Shape: (1379, 7)

===== Missing Values =====
0

===== Infinite Values =====
0

===== Data Types =====
IPChanged                  int64
BrowserChanged             int64
StateChanged               int64
LoginFailure               int64
TimeDifferenceMinutes    float64
DistanceKM               float64
TravelSpeedKMH           float64
dtype: object

===== Constant Features =====
[]

===== Feature Statistics =====

,count,mean,std,min,25%,50%,75%,max
IPChanged,1379.0,0.430022,0.495258,0.0,0.000000,0.000000,1.000000,1.000000
BrowserChanged,1379.0,0.330674,0.470627,0.0,0.000000,0.000000,1.000000,1.000000
StateChanged,1379.0,0.646846,0.478124,0.0,0.000000,1.000000,1.000000,1.000000
LoginFailure,1379.0,0.260334,0.438976,0.0,0.000000,0.000000,1.000000,1.000000
TimeDifferenceMinutes,1379.0,68530.984046,105037.459220,0.0,1699.000000,24809.000000,79534.500000,595091.000000
DistanceKM,1379.0,716.386055,621.775047,0.0,1.711148,734.751083,1195.171406,1759.129952
TravelSpeedKMH,1379.0,119.615215,2748.762442,0.0,0.001245,0.469187,2.221514,95210.052879

In [48]:
print("===== Feature Correlation Analysis =====")

correlationDF = X_core.corr()

print(
    correlationDF.round(2)
)

===== Feature Correlation Analysis =====
                       IPChanged  BrowserChanged  StateChanged  LoginFailure  \
IPChanged                   1.00            0.35          0.35         -0.06
BrowserChanged              0.35            1.00          0.29         -0.03
StateChanged                0.35            0.29          1.00         -0.05
LoginFailure               -0.06           -0.03         -0.05          1.00
TimeDifferenceMinutes       0.22            0.17          0.26         -0.01
DistanceKM                  0.28            0.22          0.84         -0.06
TravelSpeedKMH             -0.03           -0.02          0.03          0.06

                       TimeDifferenceMinutes  DistanceKM  TravelSpeedKMH
IPChanged                               0.22        0.28           -0.03
BrowserChanged                          0.17        0.22           -0.02
StateChanged                            0.26        0.84            0.03
LoginFailure                           -0.01       -0.06            0.06
TimeDifferenceMinutes                   1.00        0.22           -0.03
DistanceKM                              0.22        1.00            0.03
TravelSpeedKMH                         -0.03        0.03            1.00

In [49]:
highCorrelation = (
    correlationDF
    .where(
        np.triu(
            np.ones(
                correlationDF.shape
            ),
            k=1
        ).astype(bool)
    )
    .stack()
    .reset_index()
)

highCorrelation.columns = [
    "Feature1",
    "Feature2",
    "Correlation"
]

highCorrelation = (
    highCorrelation[
        highCorrelation["Correlation"].abs() >= 0.80
    ]
    .sort_values(
        "Correlation",
        key=lambda x: x.abs(),
        ascending=False
    )
)

print("\n===== Highly Correlated Features =====")

print(
    highCorrelation
)

===== Highly Correlated Features =====
        Feature1    Feature2  Correlation
13  StateChanged  DistanceKM     0.839196

In [50]:
print("===== New Isolation Forest Training =====")

# Final 7 ML features
X_core = coreMLDF[coreFeatureColumns].copy()

print("Training Data Shape:", X_core.shape)

# --------------------------------------------------
# Train New Model
# --------------------------------------------------

coreModel = IsolationForest(
    n_estimators=200,
    contamination=0.05,
    random_state=42
)

coreModel.fit(X_core)

print("\nNew model training completed.")
print("Features used:", len(coreFeatureColumns))
print(coreFeatureColumns)

===== New Isolation Forest Training =====
Training Data Shape: (1379, 7)

New model training completed.
Features used: 7
['IPChanged', 'BrowserChanged', 'StateChanged', 'LoginFailure', 'TimeDifferenceMinutes', 'DistanceKM', 'TravelSpeedKMH']

In [51]:
print("===== New Model Prediction =====")

# Prediction on training data
coreMLDF["Prediction"] = coreModel.predict(X_core)

print("\n===== Prediction Distribution =====")

print(
    coreMLDF["Prediction"]
    .value_counts()
)

# Percentage
predictionSummary = (
    coreMLDF["Prediction"]
    .value_counts()
    .rename_axis("Prediction")
    .reset_index(name="Count")
)

predictionSummary["Percentage"] = (
    predictionSummary["Count"]
    / len(coreMLDF)
    * 100
)

print("\n===== Prediction Summary =====")

print(
    predictionSummary.round(2)
)

===== New Model Prediction =====

===== Prediction Distribution =====
Prediction
 1    1310
-1      69
Name: count, dtype: int64

===== Prediction Summary =====
   Prediction  Count  Percentage
0           1   1310        95.0
1          -1     69         5.0

In [82]:
print("===== Preparing Unseen Data for New Model =====")

X_test_core = testMLDF[
    coreFeatureColumns
].copy()

print("Test Shape:", X_test_core.shape)

print("\nFeatures:")
print(X_test_core.columns.tolist())

print("\nMissing Values:")
print(X_test_core.isnull().sum().sum())

print("\nInfinite Values:")
print(np.isinf(X_test_core).sum().sum())

===== Preparing Unseen Data for New Model =====
Test Shape: (500, 7)

Features:
['IPChanged', 'BrowserChanged', 'StateChanged', 'LoginFailure', 'TimeDifferenceMinutes', 'DistanceKM', 'TravelSpeedKMH']

Missing Values:
0

Infinite Values:
0

In [83]:
print("===== New Model Prediction on Unseen Data =====")

# Use the NEW 7-feature model
testMLDF["CorePrediction"] = (
    coreModel.predict(X_test_core)
)

print("\n===== Prediction Distribution =====")

print(
    testMLDF["CorePrediction"]
    .value_counts()
)


# Percentage
coreTestSummary = (
    testMLDF["CorePrediction"]
    .value_counts()
    .rename_axis("Prediction")
    .reset_index(name="Count")
)

coreTestSummary["Percentage"] = (
    coreTestSummary["Count"]
    / len(testMLDF)
    * 100
)

print("\n===== Unseen Data Prediction Summary =====")

print(
    coreTestSummary.round(2)
)


# Show sample
print("\n===== Sample Predictions =====")

display(
    testMLDF[
        [
            "UserName",
            "LoginTime",
            "CorePrediction"
        ]
    ].head(20)
)

===== New Model Prediction on Unseen Data =====

===== Prediction Distribution =====
CorePrediction
 1    491
-1      9
Name: count, dtype: int64

===== Unseen Data Prediction Summary =====
   Prediction  Count  Percentage
0           1    491        98.2
1          -1      9         1.8

===== Sample Predictions =====

    UserName           LoginTime  CorePrediction
0     user_1 2027-05-27 19:16:00               1
1    user_10 2027-05-16 06:01:00               1
2   user_100 2027-05-23 19:07:00               1
3   user_104 2027-05-14 18:25:00               1
4   user_105 2027-05-20 20:34:00               1
5   user_106 2027-05-22 12:09:00               1
6   user_110 2027-05-03 16:15:00               1
7   user_110 2027-05-20 00:41:00               1
8   user_110 2027-05-23 02:34:00               1
9   user_112 2027-05-05 13:06:00               1
10  user_118 2027-05-27 18:00:00               1
11   user_12 2027-05-11 23:58:00               1
12  user_120 2027-05-23 14:24:00               1
13  user_121 2027-05-08 04:28:00               1
14  user_124 2027-05-06 23:56:00               1
15  user_125 2027-05-26 04:37:00               1
16  user_126 2027-05-07 16:51:00               1
17  user_126 2027-05-09 04:00:00              -1
18  user_127 2027-05-19 04:19:00               1
19  user_131 2027-05-17 09:31:00               1

In [84]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("===== New Model Evaluation on Unseen Data =====")

# Actual labels ko Isolation Forest format me convert karo
# 0 = Normal    -> 1
# 1 = Anomaly   -> -1

y_true_core = (
    testMLDF["ActualLabel"]
    .map({
        0: 1,
        1: -1
    })
)

# New model predictions
y_pred_core = testMLDF["CorePrediction"]


# --------------------------------------------------
# Accuracy
# --------------------------------------------------

accuracy_core = accuracy_score(
    y_true_core,
    y_pred_core
)


# --------------------------------------------------
# Precision
# --------------------------------------------------

precision_core = precision_score(
    y_true_core,
    y_pred_core,
    pos_label=-1,
    zero_division=0
)


# --------------------------------------------------
# Recall
# --------------------------------------------------

recall_core = recall_score(
    y_true_core,
    y_pred_core,
    pos_label=-1,
    zero_division=0
)


# --------------------------------------------------
# F1 Score
# --------------------------------------------------

f1_core = f1_score(
    y_true_core,
    y_pred_core,
    pos_label=-1,
    zero_division=0
)


# --------------------------------------------------
# Performance
# --------------------------------------------------

print("\n===== Performance Metrics =====")

print(
    "Accuracy :", round(accuracy_core * 100, 2), "%"
)

print(
    "Precision:", round(precision_core * 100, 2), "%"
)

print(
    "Recall   :", round(recall_core * 100, 2), "%"
)

print(
    "F1 Score :", round(f1_core * 100, 2), "%"
)


# --------------------------------------------------
# Confusion Matrix
# --------------------------------------------------

cm_core = confusion_matrix(
    y_true_core,
    y_pred_core,
    labels=[1, -1]
)

print("\n===== Confusion Matrix =====")

print(
    pd.DataFrame(
        cm_core,
        index=[
            "Actual Normal",
            "Actual Anomaly"
        ],
        columns=[
            "Predicted Normal",
            "Predicted Anomaly"
        ]
    )
)

===== New Model Evaluation on Unseen Data =====

===== Performance Metrics =====
Accuracy : 89.2 %
Precision: 33.33 %
Recall   : 5.88 %
F1 Score : 10.0 %

===== Confusion Matrix =====
                Predicted Normal  Predicted Anomaly
Actual Normal                443                  6
Actual Anomaly                48                  3